/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mt_proto_ld100.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mt_proto_ld100.pb-c.h"
void   mt_ld100__get_addr_req__init
                     (MtLd100__GetAddrReq         *message)
{
  static const MtLd100__GetAddrReq init_value = MT_LD100__GET_ADDR_REQ__INIT;
  *message = init_value;
}
size_t mt_ld100__get_addr_req__get_packed_size
                     (const MtLd100__GetAddrReq *message)
{
  assert(message->base.descriptor == &mt_ld100__get_addr_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_ld100__get_addr_req__pack
                     (const MtLd100__GetAddrReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_ld100__get_addr_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_ld100__get_addr_req__pack_to_buffer
                     (const MtLd100__GetAddrReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_ld100__get_addr_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtLd100__GetAddrReq *
       mt_ld100__get_addr_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtLd100__GetAddrReq *)
     protobuf_c_message_unpack (&mt_ld100__get_addr_req__descriptor,
                                allocator, len, data);
}
void   mt_ld100__get_addr_req__free_unpacked
                     (MtLd100__GetAddrReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_ld100__get_addr_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_ld100__get_addr_res__init
                     (MtLd100__GetAddrRes         *message)
{
  static const MtLd100__GetAddrRes init_value = MT_LD100__GET_ADDR_RES__INIT;
  *message = init_value;
}
size_t mt_ld100__get_addr_res__get_packed_size
                     (const MtLd100__GetAddrRes *message)
{
  assert(message->base.descriptor == &mt_ld100__get_addr_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_ld100__get_addr_res__pack
                     (const MtLd100__GetAddrRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_ld100__get_addr_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_ld100__get_addr_res__pack_to_buffer
                     (const MtLd100__GetAddrRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_ld100__get_addr_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtLd100__GetAddrRes *
       mt_ld100__get_addr_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtLd100__GetAddrRes *)
     protobuf_c_message_unpack (&mt_ld100__get_addr_res__descriptor,
                                allocator, len, data);
}
void   mt_ld100__get_addr_res__free_unpacked
                     (MtLd100__GetAddrRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_ld100__get_addr_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_ld100__set_addr_req__init
                     (MtLd100__SetAddrReq         *message)
{
  static const MtLd100__SetAddrReq init_value = MT_LD100__SET_ADDR_REQ__INIT;
  *message = init_value;
}
size_t mt_ld100__set_addr_req__get_packed_size
                     (const MtLd100__SetAddrReq *message)
{
  assert(message->base.descriptor == &mt_ld100__set_addr_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_ld100__set_addr_req__pack
                     (const MtLd100__SetAddrReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_ld100__set_addr_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_ld100__set_addr_req__pack_to_buffer
                     (const MtLd100__SetAddrReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_ld100__set_addr_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtLd100__SetAddrReq *
       mt_ld100__set_addr_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtLd100__SetAddrReq *)
     protobuf_c_message_unpack (&mt_ld100__set_addr_req__descriptor,
                                allocator, len, data);
}
void   mt_ld100__set_addr_req__free_unpacked
                     (MtLd100__SetAddrReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_ld100__set_addr_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_ld100__set_addr_res__init
                     (MtLd100__SetAddrRes         *message)
{
  static const MtLd100__SetAddrRes init_value = MT_LD100__SET_ADDR_RES__INIT;
  *message = init_value;
}
size_t mt_ld100__set_addr_res__get_packed_size
                     (const MtLd100__SetAddrRes *message)
{
  assert(message->base.descriptor == &mt_ld100__set_addr_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_ld100__set_addr_res__pack
                     (const MtLd100__SetAddrRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_ld100__set_addr_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_ld100__set_addr_res__pack_to_buffer
                     (const MtLd100__SetAddrRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_ld100__set_addr_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtLd100__SetAddrRes *
       mt_ld100__set_addr_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtLd100__SetAddrRes *)
     protobuf_c_message_unpack (&mt_ld100__set_addr_res__descriptor,
                                allocator, len, data);
}
void   mt_ld100__set_addr_res__free_unpacked
                     (MtLd100__SetAddrRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_ld100__set_addr_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_ld100__state__init
                     (MtLd100__State         *message)
{
  static const MtLd100__State init_value = MT_LD100__STATE__INIT;
  *message = init_value;
}
size_t mt_ld100__state__get_packed_size
                     (const MtLd100__State *message)
{
  assert(message->base.descriptor == &mt_ld100__state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_ld100__state__pack
                     (const MtLd100__State *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_ld100__state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_ld100__state__pack_to_buffer
                     (const MtLd100__State *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_ld100__state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtLd100__State *
       mt_ld100__state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtLd100__State *)
     protobuf_c_message_unpack (&mt_ld100__state__descriptor,
                                allocator, len, data);
}
void   mt_ld100__state__free_unpacked
                     (MtLd100__State *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_ld100__state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_ld100__get_state_req__init
                     (MtLd100__GetStateReq         *message)
{
  static const MtLd100__GetStateReq init_value = MT_LD100__GET_STATE_REQ__INIT;
  *message = init_value;
}
size_t mt_ld100__get_state_req__get_packed_size
                     (const MtLd100__GetStateReq *message)
{
  assert(message->base.descriptor == &mt_ld100__get_state_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_ld100__get_state_req__pack
                     (const MtLd100__GetStateReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_ld100__get_state_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_ld100__get_state_req__pack_to_buffer
                     (const MtLd100__GetStateReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_ld100__get_state_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtLd100__GetStateReq *
       mt_ld100__get_state_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtLd100__GetStateReq *)
     protobuf_c_message_unpack (&mt_ld100__get_state_req__descriptor,
                                allocator, len, data);
}
void   mt_ld100__get_state_req__free_unpacked
                     (MtLd100__GetStateReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_ld100__get_state_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_ld100__get_state_res__init
                     (MtLd100__GetStateRes         *message)
{
  static const MtLd100__GetStateRes init_value = MT_LD100__GET_STATE_RES__INIT;
  *message = init_value;
}
size_t mt_ld100__get_state_res__get_packed_size
                     (const MtLd100__GetStateRes *message)
{
  assert(message->base.descriptor == &mt_ld100__get_state_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_ld100__get_state_res__pack
                     (const MtLd100__GetStateRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_ld100__get_state_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_ld100__get_state_res__pack_to_buffer
                     (const MtLd100__GetStateRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_ld100__get_state_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtLd100__GetStateRes *
       mt_ld100__get_state_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtLd100__GetStateRes *)
     protobuf_c_message_unpack (&mt_ld100__get_state_res__descriptor,
                                allocator, len, data);
}
void   mt_ld100__get_state_res__free_unpacked
                     (MtLd100__GetStateRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_ld100__get_state_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_ld100__get_relay_req__init
                     (MtLd100__GetRelayReq         *message)
{
  static const MtLd100__GetRelayReq init_value = MT_LD100__GET_RELAY_REQ__INIT;
  *message = init_value;
}
size_t mt_ld100__get_relay_req__get_packed_size
                     (const MtLd100__GetRelayReq *message)
{
  assert(message->base.descriptor == &mt_ld100__get_relay_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_ld100__get_relay_req__pack
                     (const MtLd100__GetRelayReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_ld100__get_relay_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_ld100__get_relay_req__pack_to_buffer
                     (const MtLd100__GetRelayReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_ld100__get_relay_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtLd100__GetRelayReq *
       mt_ld100__get_relay_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtLd100__GetRelayReq *)
     protobuf_c_message_unpack (&mt_ld100__get_relay_req__descriptor,
                                allocator, len, data);
}
void   mt_ld100__get_relay_req__free_unpacked
                     (MtLd100__GetRelayReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_ld100__get_relay_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_ld100__get_relay_res__init
                     (MtLd100__GetRelayRes         *message)
{
  static const MtLd100__GetRelayRes init_value = MT_LD100__GET_RELAY_RES__INIT;
  *message = init_value;
}
size_t mt_ld100__get_relay_res__get_packed_size
                     (const MtLd100__GetRelayRes *message)
{
  assert(message->base.descriptor == &mt_ld100__get_relay_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_ld100__get_relay_res__pack
                     (const MtLd100__GetRelayRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_ld100__get_relay_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_ld100__get_relay_res__pack_to_buffer
                     (const MtLd100__GetRelayRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_ld100__get_relay_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtLd100__GetRelayRes *
       mt_ld100__get_relay_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtLd100__GetRelayRes *)
     protobuf_c_message_unpack (&mt_ld100__get_relay_res__descriptor,
                                allocator, len, data);
}
void   mt_ld100__get_relay_res__free_unpacked
                     (MtLd100__GetRelayRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_ld100__get_relay_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_ld100__set_relay_req__init
                     (MtLd100__SetRelayReq         *message)
{
  static const MtLd100__SetRelayReq init_value = MT_LD100__SET_RELAY_REQ__INIT;
  *message = init_value;
}
size_t mt_ld100__set_relay_req__get_packed_size
                     (const MtLd100__SetRelayReq *message)
{
  assert(message->base.descriptor == &mt_ld100__set_relay_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_ld100__set_relay_req__pack
                     (const MtLd100__SetRelayReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_ld100__set_relay_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_ld100__set_relay_req__pack_to_buffer
                     (const MtLd100__SetRelayReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_ld100__set_relay_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtLd100__SetRelayReq *
       mt_ld100__set_relay_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtLd100__SetRelayReq *)
     protobuf_c_message_unpack (&mt_ld100__set_relay_req__descriptor,
                                allocator, len, data);
}
void   mt_ld100__set_relay_req__free_unpacked
                     (MtLd100__SetRelayReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_ld100__set_relay_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_ld100__set_relay_res__init
                     (MtLd100__SetRelayRes         *message)
{
  static const MtLd100__SetRelayRes init_value = MT_LD100__SET_RELAY_RES__INIT;
  *message = init_value;
}
size_t mt_ld100__set_relay_res__get_packed_size
                     (const MtLd100__SetRelayRes *message)
{
  assert(message->base.descriptor == &mt_ld100__set_relay_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_ld100__set_relay_res__pack
                     (const MtLd100__SetRelayRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_ld100__set_relay_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_ld100__set_relay_res__pack_to_buffer
                     (const MtLd100__SetRelayRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_ld100__set_relay_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtLd100__SetRelayRes *
       mt_ld100__set_relay_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtLd100__SetRelayRes *)
     protobuf_c_message_unpack (&mt_ld100__set_relay_res__descriptor,
                                allocator, len, data);
}
void   mt_ld100__set_relay_res__free_unpacked
                     (MtLd100__SetRelayRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_ld100__set_relay_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mt_ld100__get_addr_req__field_descriptors[1] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__GetAddrReq, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_ld100__get_addr_req__field_indices_by_name[] = {
  0,   /* field[0] = addr */
};
static const ProtobufCIntRange mt_ld100__get_addr_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_ld100__get_addr_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_ld100.GetAddrReq",
  "GetAddrReq",
  "MtLd100__GetAddrReq",
  "mt_ld100",
  sizeof(MtLd100__GetAddrReq),
  1,
  mt_ld100__get_addr_req__field_descriptors,
  mt_ld100__get_addr_req__field_indices_by_name,
  1,  mt_ld100__get_addr_req__number_ranges,
  (ProtobufCMessageInit) mt_ld100__get_addr_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_ld100__get_addr_res__field_descriptors[3] =
{
  {
    "resCode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__GetAddrRes, rescode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__GetAddrRes, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtLd100__GetAddrRes, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_ld100__get_addr_res__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  0,   /* field[0] = resCode */
  2,   /* field[2] = state */
};
static const ProtobufCIntRange mt_ld100__get_addr_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mt_ld100__get_addr_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_ld100.GetAddrRes",
  "GetAddrRes",
  "MtLd100__GetAddrRes",
  "mt_ld100",
  sizeof(MtLd100__GetAddrRes),
  3,
  mt_ld100__get_addr_res__field_descriptors,
  mt_ld100__get_addr_res__field_indices_by_name,
  1,  mt_ld100__get_addr_res__number_ranges,
  (ProtobufCMessageInit) mt_ld100__get_addr_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_ld100__set_addr_req__field_descriptors[1] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__SetAddrReq, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_ld100__set_addr_req__field_indices_by_name[] = {
  0,   /* field[0] = addr */
};
static const ProtobufCIntRange mt_ld100__set_addr_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_ld100__set_addr_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_ld100.SetAddrReq",
  "SetAddrReq",
  "MtLd100__SetAddrReq",
  "mt_ld100",
  sizeof(MtLd100__SetAddrReq),
  1,
  mt_ld100__set_addr_req__field_descriptors,
  mt_ld100__set_addr_req__field_indices_by_name,
  1,  mt_ld100__set_addr_req__number_ranges,
  (ProtobufCMessageInit) mt_ld100__set_addr_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_ld100__set_addr_res__field_descriptors[1] =
{
  {
    "resCode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__SetAddrRes, rescode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_ld100__set_addr_res__field_indices_by_name[] = {
  0,   /* field[0] = resCode */
};
static const ProtobufCIntRange mt_ld100__set_addr_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_ld100__set_addr_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_ld100.SetAddrRes",
  "SetAddrRes",
  "MtLd100__SetAddrRes",
  "mt_ld100",
  sizeof(MtLd100__SetAddrRes),
  1,
  mt_ld100__set_addr_res__field_descriptors,
  mt_ld100__set_addr_res__field_indices_by_name,
  1,  mt_ld100__set_addr_res__number_ranges,
  (ProtobufCMessageInit) mt_ld100__set_addr_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_ld100__state__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtLd100__State, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_ld100__state__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange mt_ld100__state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_ld100__state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_ld100.State",
  "State",
  "MtLd100__State",
  "mt_ld100",
  sizeof(MtLd100__State),
  1,
  mt_ld100__state__field_descriptors,
  mt_ld100__state__field_indices_by_name,
  1,  mt_ld100__state__number_ranges,
  (ProtobufCMessageInit) mt_ld100__state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_ld100__get_state_req__field_descriptors[1] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__GetStateReq, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_ld100__get_state_req__field_indices_by_name[] = {
  0,   /* field[0] = addr */
};
static const ProtobufCIntRange mt_ld100__get_state_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_ld100__get_state_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_ld100.GetStateReq",
  "GetStateReq",
  "MtLd100__GetStateReq",
  "mt_ld100",
  sizeof(MtLd100__GetStateReq),
  1,
  mt_ld100__get_state_req__field_descriptors,
  mt_ld100__get_state_req__field_indices_by_name,
  1,  mt_ld100__get_state_req__number_ranges,
  (ProtobufCMessageInit) mt_ld100__get_state_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_ld100__get_state_res__field_descriptors[3] =
{
  {
    "resCode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__GetStateRes, rescode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__GetStateRes, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtLd100__GetStateRes, state),
    &mt_ld100__state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_ld100__get_state_res__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  0,   /* field[0] = resCode */
  2,   /* field[2] = state */
};
static const ProtobufCIntRange mt_ld100__get_state_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mt_ld100__get_state_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_ld100.GetStateRes",
  "GetStateRes",
  "MtLd100__GetStateRes",
  "mt_ld100",
  sizeof(MtLd100__GetStateRes),
  3,
  mt_ld100__get_state_res__field_descriptors,
  mt_ld100__get_state_res__field_indices_by_name,
  1,  mt_ld100__get_state_res__number_ranges,
  (ProtobufCMessageInit) mt_ld100__get_state_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_ld100__get_relay_req__field_descriptors[1] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__GetRelayReq, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_ld100__get_relay_req__field_indices_by_name[] = {
  0,   /* field[0] = addr */
};
static const ProtobufCIntRange mt_ld100__get_relay_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_ld100__get_relay_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_ld100.GetRelayReq",
  "GetRelayReq",
  "MtLd100__GetRelayReq",
  "mt_ld100",
  sizeof(MtLd100__GetRelayReq),
  1,
  mt_ld100__get_relay_req__field_descriptors,
  mt_ld100__get_relay_req__field_indices_by_name,
  1,  mt_ld100__get_relay_req__number_ranges,
  (ProtobufCMessageInit) mt_ld100__get_relay_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_ld100__get_relay_res__field_descriptors[3] =
{
  {
    "resCode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__GetRelayRes, rescode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__GetRelayRes, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtLd100__GetRelayRes, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_ld100__get_relay_res__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  0,   /* field[0] = resCode */
  2,   /* field[2] = state */
};
static const ProtobufCIntRange mt_ld100__get_relay_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mt_ld100__get_relay_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_ld100.GetRelayRes",
  "GetRelayRes",
  "MtLd100__GetRelayRes",
  "mt_ld100",
  sizeof(MtLd100__GetRelayRes),
  3,
  mt_ld100__get_relay_res__field_descriptors,
  mt_ld100__get_relay_res__field_indices_by_name,
  1,  mt_ld100__get_relay_res__number_ranges,
  (ProtobufCMessageInit) mt_ld100__get_relay_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_ld100__set_relay_req__field_descriptors[1] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__SetRelayReq, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_ld100__set_relay_req__field_indices_by_name[] = {
  0,   /* field[0] = addr */
};
static const ProtobufCIntRange mt_ld100__set_relay_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_ld100__set_relay_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_ld100.SetRelayReq",
  "SetRelayReq",
  "MtLd100__SetRelayReq",
  "mt_ld100",
  sizeof(MtLd100__SetRelayReq),
  1,
  mt_ld100__set_relay_req__field_descriptors,
  mt_ld100__set_relay_req__field_indices_by_name,
  1,  mt_ld100__set_relay_req__number_ranges,
  (ProtobufCMessageInit) mt_ld100__set_relay_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_ld100__set_relay_res__field_descriptors[1] =
{
  {
    "resCode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtLd100__SetRelayRes, rescode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_ld100__set_relay_res__field_indices_by_name[] = {
  0,   /* field[0] = resCode */
};
static const ProtobufCIntRange mt_ld100__set_relay_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_ld100__set_relay_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_ld100.SetRelayRes",
  "SetRelayRes",
  "MtLd100__SetRelayRes",
  "mt_ld100",
  sizeof(MtLd100__SetRelayRes),
  1,
  mt_ld100__set_relay_res__field_descriptors,
  mt_ld100__set_relay_res__field_indices_by_name,
  1,  mt_ld100__set_relay_res__number_ranges,
  (ProtobufCMessageInit) mt_ld100__set_relay_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor mt_ld100__ld100_service__method_descriptors[5] =
{
  { "GetAddr", &mt_ld100__get_addr_req__descriptor, &mt_ld100__get_addr_res__descriptor },
  { "SetAddr", &mt_ld100__set_addr_req__descriptor, &mt_ld100__set_addr_res__descriptor },
  { "GetState", &mt_ld100__get_state_req__descriptor, &mt_ld100__get_state_req__descriptor },
  { "GetRelay", &mt_ld100__get_relay_req__descriptor, &mt_ld100__get_relay_res__descriptor },
  { "SetRelay", &mt_ld100__set_relay_req__descriptor, &mt_ld100__set_relay_res__descriptor },
};
const unsigned mt_ld100__ld100_service__method_indices_by_name[] = {
  0,        /* GetAddr */
  3,        /* GetRelay */
  2,        /* GetState */
  1,        /* SetAddr */
  4         /* SetRelay */
};
const ProtobufCServiceDescriptor mt_ld100__ld100_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "mt_ld100.ld100Service",
  "ld100Service",
  "MtLd100__Ld100Service",
  "mt_ld100",
  5,
  mt_ld100__ld100_service__method_descriptors,
  mt_ld100__ld100_service__method_indices_by_name
};
void mt_ld100__ld100_service__get_addr(ProtobufCService *service,
                                       const MtLd100__GetAddrReq *input,
                                       MtLd100__GetAddrRes_Closure closure,
                                       void *closure_data)
{
  assert(service->descriptor == &mt_ld100__ld100_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_ld100__ld100_service__set_addr(ProtobufCService *service,
                                       const MtLd100__SetAddrReq *input,
                                       MtLd100__SetAddrRes_Closure closure,
                                       void *closure_data)
{
  assert(service->descriptor == &mt_ld100__ld100_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_ld100__ld100_service__get_state(ProtobufCService *service,
                                        const MtLd100__GetStateReq *input,
                                        MtLd100__GetStateReq_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &mt_ld100__ld100_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_ld100__ld100_service__get_relay(ProtobufCService *service,
                                        const MtLd100__GetRelayReq *input,
                                        MtLd100__GetRelayRes_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &mt_ld100__ld100_service__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_ld100__ld100_service__set_relay(ProtobufCService *service,
                                        const MtLd100__SetRelayReq *input,
                                        MtLd100__SetRelayRes_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &mt_ld100__ld100_service__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_ld100__ld100_service__init (MtLd100__Ld100Service_Service *service,
                                    MtLd100__Ld100Service_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &mt_ld100__ld100_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
