// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mt_proto_ktc_n01.proto

package mt_ktc_n01

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetCmdRes struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCmdRes) Reset()         { *m = SetCmdRes{} }
func (m *SetCmdRes) String() string { return proto.CompactTextString(m) }
func (*SetCmdRes) ProtoMessage()    {}
func (*SetCmdRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a740d8a571cc332, []int{0}
}

func (m *SetCmdRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCmdRes.Unmarshal(m, b)
}
func (m *SetCmdRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCmdRes.Marshal(b, m, deterministic)
}
func (m *SetCmdRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCmdRes.Merge(m, src)
}
func (m *SetCmdRes) XXX_Size() int {
	return xxx_messageInfo_SetCmdRes.Size(m)
}
func (m *SetCmdRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCmdRes.DiscardUnknown(m)
}

var xxx_messageInfo_SetCmdRes proto.InternalMessageInfo

func (m *SetCmdRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SetCmdRes) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 发送命令
// 101   开机制冷
// 102   开机制热
// 103   关机
// 01-20 自定义命令
type SetCmdReq struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Cmd                  int32    `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCmdReq) Reset()         { *m = SetCmdReq{} }
func (m *SetCmdReq) String() string { return proto.CompactTextString(m) }
func (*SetCmdReq) ProtoMessage()    {}
func (*SetCmdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a740d8a571cc332, []int{1}
}

func (m *SetCmdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCmdReq.Unmarshal(m, b)
}
func (m *SetCmdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCmdReq.Marshal(b, m, deterministic)
}
func (m *SetCmdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCmdReq.Merge(m, src)
}
func (m *SetCmdReq) XXX_Size() int {
	return xxx_messageInfo_SetCmdReq.Size(m)
}
func (m *SetCmdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCmdReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetCmdReq proto.InternalMessageInfo

func (m *SetCmdReq) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *SetCmdReq) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func init() {
	proto.RegisterType((*SetCmdRes)(nil), "mt_ktc_n01.SetCmdRes")
	proto.RegisterType((*SetCmdReq)(nil), "mt_ktc_n01.SetCmdReq")
}

func init() { proto.RegisterFile("mt_proto_ktc_n01.proto", fileDescriptor_8a740d8a571cc332) }

var fileDescriptor_8a740d8a571cc332 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0x2d, 0x89, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0x8f, 0xcf, 0x2e, 0x49, 0x8e, 0xcf, 0x33, 0x30, 0xd4, 0x03, 0xf3, 0x84,
	0xb8, 0x72, 0x4b, 0x60, 0x22, 0x4a, 0x96, 0x5c, 0x9c, 0xc1, 0xa9, 0x25, 0xce, 0xb9, 0x29, 0x41,
	0xa9, 0xc5, 0x42, 0x42, 0x5c, 0x2c, 0xc9, 0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac,
	0x41, 0x60, 0xb6, 0x90, 0x04, 0x17, 0x7b, 0x72, 0x7e, 0x5e, 0x49, 0x6a, 0x5e, 0x89, 0x04, 0x93,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0xab, 0x64, 0x88, 0xd0, 0x5a, 0x08, 0xd2, 0x5a, 0x90, 0x5f,
	0x54, 0x02, 0xd3, 0x0a, 0x62, 0x0b, 0x09, 0x70, 0x31, 0x27, 0xe7, 0xa6, 0x80, 0xb5, 0xb1, 0x06,
	0x81, 0x98, 0x46, 0xce, 0x5c, 0xec, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x16, 0x5c,
	0x6c, 0x10, 0xdd, 0x42, 0xa2, 0x7a, 0x08, 0xf7, 0xe8, 0xc1, 0x4d, 0x94, 0xc2, 0x2a, 0x5c, 0xac,
	0xc4, 0x90, 0xc4, 0x06, 0xf6, 0x85, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x02, 0x02, 0x4c,
	0xdf, 0x00, 0x00, 0x00,
}
