/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: unary_call.proto */

#ifndef PROTOBUF_C_unary_5fcall_2eproto__INCLUDED
#define PROTOBUF_C_unary_5fcall_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/wrappers.pb-c.h"
#include "google/protobuf/any.pb-c.h"

typedef struct _Ai__Metathings__Component__UnaryCallRequest Ai__Metathings__Component__UnaryCallRequest;
typedef struct _Ai__Metathings__Component__UnaryCallResponse Ai__Metathings__Component__UnaryCallResponse;


/* --- enums --- */


/* --- messages --- */

struct  _Ai__Metathings__Component__UnaryCallRequest
{
  ProtobufCMessage base;
  Google__Protobuf__StringValue *method;
  Google__Protobuf__Any *value;
};
#define AI__METATHINGS__COMPONENT__UNARY_CALL_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ai__metathings__component__unary_call_request__descriptor) \
    , NULL, NULL }


struct  _Ai__Metathings__Component__UnaryCallResponse
{
  ProtobufCMessage base;
  char *method;
  Google__Protobuf__Any *value;
};
#define AI__METATHINGS__COMPONENT__UNARY_CALL_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ai__metathings__component__unary_call_response__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


/* Ai__Metathings__Component__UnaryCallRequest methods */
void   ai__metathings__component__unary_call_request__init
                     (Ai__Metathings__Component__UnaryCallRequest         *message);
size_t ai__metathings__component__unary_call_request__get_packed_size
                     (const Ai__Metathings__Component__UnaryCallRequest   *message);
size_t ai__metathings__component__unary_call_request__pack
                     (const Ai__Metathings__Component__UnaryCallRequest   *message,
                      uint8_t             *out);
size_t ai__metathings__component__unary_call_request__pack_to_buffer
                     (const Ai__Metathings__Component__UnaryCallRequest   *message,
                      ProtobufCBuffer     *buffer);
Ai__Metathings__Component__UnaryCallRequest *
       ai__metathings__component__unary_call_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ai__metathings__component__unary_call_request__free_unpacked
                     (Ai__Metathings__Component__UnaryCallRequest *message,
                      ProtobufCAllocator *allocator);
/* Ai__Metathings__Component__UnaryCallResponse methods */
void   ai__metathings__component__unary_call_response__init
                     (Ai__Metathings__Component__UnaryCallResponse         *message);
size_t ai__metathings__component__unary_call_response__get_packed_size
                     (const Ai__Metathings__Component__UnaryCallResponse   *message);
size_t ai__metathings__component__unary_call_response__pack
                     (const Ai__Metathings__Component__UnaryCallResponse   *message,
                      uint8_t             *out);
size_t ai__metathings__component__unary_call_response__pack_to_buffer
                     (const Ai__Metathings__Component__UnaryCallResponse   *message,
                      ProtobufCBuffer     *buffer);
Ai__Metathings__Component__UnaryCallResponse *
       ai__metathings__component__unary_call_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ai__metathings__component__unary_call_response__free_unpacked
                     (Ai__Metathings__Component__UnaryCallResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ai__Metathings__Component__UnaryCallRequest_Closure)
                 (const Ai__Metathings__Component__UnaryCallRequest *message,
                  void *closure_data);
typedef void (*Ai__Metathings__Component__UnaryCallResponse_Closure)
                 (const Ai__Metathings__Component__UnaryCallResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ai__metathings__component__unary_call_request__descriptor;
extern const ProtobufCMessageDescriptor ai__metathings__component__unary_call_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_unary_5fcall_2eproto__INCLUDED */
