#V := 1
PROJECT_NAME := example-rs232-lora-ebyte-server

EXTRA_COMPONENT_DIRS := $(CURDIR)/../../../components
EXTRA_COMPONENT_DIRS += $(CURDIR)/../../../mt_proto

include $(IDF_PATH)/make/project.mk
