/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mt_proto_EA900II.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mt_proto_EA900II.pb-c.h"
void   mt__ea900_ii__data__init
                     (MtEA900II__Data         *message)
{
  static const MtEA900II__Data init_value = MT__EA900_II__DATA__INIT;
  *message = init_value;
}
size_t mt__ea900_ii__data__get_packed_size
                     (const MtEA900II__Data *message)
{
  assert(message->base.descriptor == &mt__ea900_ii__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt__ea900_ii__data__pack
                     (const MtEA900II__Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt__ea900_ii__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt__ea900_ii__data__pack_to_buffer
                     (const MtEA900II__Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt__ea900_ii__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtEA900II__Data *
       mt__ea900_ii__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtEA900II__Data *)
     protobuf_c_message_unpack (&mt__ea900_ii__data__descriptor,
                                allocator, len, data);
}
void   mt__ea900_ii__data__free_unpacked
                     (MtEA900II__Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt__ea900_ii__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt__ea900_ii__model__init
                     (MtEA900II__Model         *message)
{
  static const MtEA900II__Model init_value = MT__EA900_II__MODEL__INIT;
  *message = init_value;
}
size_t mt__ea900_ii__model__get_packed_size
                     (const MtEA900II__Model *message)
{
  assert(message->base.descriptor == &mt__ea900_ii__model__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt__ea900_ii__model__pack
                     (const MtEA900II__Model *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt__ea900_ii__model__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt__ea900_ii__model__pack_to_buffer
                     (const MtEA900II__Model *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt__ea900_ii__model__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtEA900II__Model *
       mt__ea900_ii__model__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtEA900II__Model *)
     protobuf_c_message_unpack (&mt__ea900_ii__model__descriptor,
                                allocator, len, data);
}
void   mt__ea900_ii__model__free_unpacked
                     (MtEA900II__Model *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt__ea900_ii__model__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt__ea900_ii__config__init
                     (MtEA900II__Config         *message)
{
  static const MtEA900II__Config init_value = MT__EA900_II__CONFIG__INIT;
  *message = init_value;
}
size_t mt__ea900_ii__config__get_packed_size
                     (const MtEA900II__Config *message)
{
  assert(message->base.descriptor == &mt__ea900_ii__config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt__ea900_ii__config__pack
                     (const MtEA900II__Config *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt__ea900_ii__config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt__ea900_ii__config__pack_to_buffer
                     (const MtEA900II__Config *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt__ea900_ii__config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtEA900II__Config *
       mt__ea900_ii__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtEA900II__Config *)
     protobuf_c_message_unpack (&mt__ea900_ii__config__descriptor,
                                allocator, len, data);
}
void   mt__ea900_ii__config__free_unpacked
                     (MtEA900II__Config *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt__ea900_ii__config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt__ea900_ii__data_res__init
                     (MtEA900II__DataRes         *message)
{
  static const MtEA900II__DataRes init_value = MT__EA900_II__DATA_RES__INIT;
  *message = init_value;
}
size_t mt__ea900_ii__data_res__get_packed_size
                     (const MtEA900II__DataRes *message)
{
  assert(message->base.descriptor == &mt__ea900_ii__data_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt__ea900_ii__data_res__pack
                     (const MtEA900II__DataRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt__ea900_ii__data_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt__ea900_ii__data_res__pack_to_buffer
                     (const MtEA900II__DataRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt__ea900_ii__data_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtEA900II__DataRes *
       mt__ea900_ii__data_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtEA900II__DataRes *)
     protobuf_c_message_unpack (&mt__ea900_ii__data_res__descriptor,
                                allocator, len, data);
}
void   mt__ea900_ii__data_res__free_unpacked
                     (MtEA900II__DataRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt__ea900_ii__data_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt__ea900_ii__model_res__init
                     (MtEA900II__ModelRes         *message)
{
  static const MtEA900II__ModelRes init_value = MT__EA900_II__MODEL_RES__INIT;
  *message = init_value;
}
size_t mt__ea900_ii__model_res__get_packed_size
                     (const MtEA900II__ModelRes *message)
{
  assert(message->base.descriptor == &mt__ea900_ii__model_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt__ea900_ii__model_res__pack
                     (const MtEA900II__ModelRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt__ea900_ii__model_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt__ea900_ii__model_res__pack_to_buffer
                     (const MtEA900II__ModelRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt__ea900_ii__model_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtEA900II__ModelRes *
       mt__ea900_ii__model_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtEA900II__ModelRes *)
     protobuf_c_message_unpack (&mt__ea900_ii__model_res__descriptor,
                                allocator, len, data);
}
void   mt__ea900_ii__model_res__free_unpacked
                     (MtEA900II__ModelRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt__ea900_ii__model_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt__ea900_ii__config_res__init
                     (MtEA900II__ConfigRes         *message)
{
  static const MtEA900II__ConfigRes init_value = MT__EA900_II__CONFIG_RES__INIT;
  *message = init_value;
}
size_t mt__ea900_ii__config_res__get_packed_size
                     (const MtEA900II__ConfigRes *message)
{
  assert(message->base.descriptor == &mt__ea900_ii__config_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt__ea900_ii__config_res__pack
                     (const MtEA900II__ConfigRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt__ea900_ii__config_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt__ea900_ii__config_res__pack_to_buffer
                     (const MtEA900II__ConfigRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt__ea900_ii__config_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtEA900II__ConfigRes *
       mt__ea900_ii__config_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtEA900II__ConfigRes *)
     protobuf_c_message_unpack (&mt__ea900_ii__config_res__descriptor,
                                allocator, len, data);
}
void   mt__ea900_ii__config_res__free_unpacked
                     (MtEA900II__ConfigRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt__ea900_ii__config_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mt__ea900_ii__data__field_descriptors[14] =
{
  {
    "votageIn",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, votagein),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "votageOut",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, votageout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadPercent",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, loadpercent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freqIn",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, freqin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "votageBat",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, votagebat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temp",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w7",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, w7),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w6",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, w6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w5",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, w5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w4",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, w4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w3",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, w3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w2",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, w2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w1",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, w1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w0",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Data, w0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt__ea900_ii__data__field_indices_by_name[] = {
  3,   /* field[3] = freqIn */
  2,   /* field[2] = loadPercent */
  5,   /* field[5] = temp */
  4,   /* field[4] = votageBat */
  0,   /* field[0] = votageIn */
  1,   /* field[1] = votageOut */
  13,   /* field[13] = w0 */
  12,   /* field[12] = w1 */
  11,   /* field[11] = w2 */
  10,   /* field[10] = w3 */
  9,   /* field[9] = w4 */
  8,   /* field[8] = w5 */
  7,   /* field[7] = w6 */
  6,   /* field[6] = w7 */
};
static const ProtobufCIntRange mt__ea900_ii__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor mt__ea900_ii__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_EA900II.Data",
  "Data",
  "MtEA900II__Data",
  "mt_EA900II",
  sizeof(MtEA900II__Data),
  14,
  mt__ea900_ii__data__field_descriptors,
  mt__ea900_ii__data__field_indices_by_name,
  1,  mt__ea900_ii__data__number_ranges,
  (ProtobufCMessageInit) mt__ea900_ii__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt__ea900_ii__model__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Model, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Model, model),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Model, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt__ea900_ii__model__field_indices_by_name[] = {
  1,   /* field[1] = model */
  0,   /* field[0] = name */
  2,   /* field[2] = version */
};
static const ProtobufCIntRange mt__ea900_ii__model__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mt__ea900_ii__model__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_EA900II.Model",
  "Model",
  "MtEA900II__Model",
  "mt_EA900II",
  sizeof(MtEA900II__Model),
  3,
  mt__ea900_ii__model__field_descriptors,
  mt__ea900_ii__model__field_indices_by_name,
  1,  mt__ea900_ii__model__number_ranges,
  (ProtobufCMessageInit) mt__ea900_ii__model__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt__ea900_ii__config__field_descriptors[4] =
{
  {
    "votage",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Config, votage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Config, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "batVotage",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Config, batvotage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__Config, freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt__ea900_ii__config__field_indices_by_name[] = {
  2,   /* field[2] = batVotage */
  1,   /* field[1] = current */
  3,   /* field[3] = freq */
  0,   /* field[0] = votage */
};
static const ProtobufCIntRange mt__ea900_ii__config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor mt__ea900_ii__config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_EA900II.Config",
  "Config",
  "MtEA900II__Config",
  "mt_EA900II",
  sizeof(MtEA900II__Config),
  4,
  mt__ea900_ii__config__field_descriptors,
  mt__ea900_ii__config__field_indices_by_name,
  1,  mt__ea900_ii__config__number_ranges,
  (ProtobufCMessageInit) mt__ea900_ii__config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt__ea900_ii__data_res__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__DataRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datas",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__DataRes, datas),
    &mt__ea900_ii__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt__ea900_ii__data_res__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = datas */
};
static const ProtobufCIntRange mt__ea900_ii__data_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mt__ea900_ii__data_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_EA900II.DataRes",
  "DataRes",
  "MtEA900II__DataRes",
  "mt_EA900II",
  sizeof(MtEA900II__DataRes),
  2,
  mt__ea900_ii__data_res__field_descriptors,
  mt__ea900_ii__data_res__field_indices_by_name,
  1,  mt__ea900_ii__data_res__number_ranges,
  (ProtobufCMessageInit) mt__ea900_ii__data_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt__ea900_ii__model_res__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__ModelRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__ModelRes, model),
    &mt__ea900_ii__model__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt__ea900_ii__model_res__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = model */
};
static const ProtobufCIntRange mt__ea900_ii__model_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mt__ea900_ii__model_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_EA900II.ModelRes",
  "ModelRes",
  "MtEA900II__ModelRes",
  "mt_EA900II",
  sizeof(MtEA900II__ModelRes),
  2,
  mt__ea900_ii__model_res__field_descriptors,
  mt__ea900_ii__model_res__field_indices_by_name,
  1,  mt__ea900_ii__model_res__number_ranges,
  (ProtobufCMessageInit) mt__ea900_ii__model_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt__ea900_ii__config_res__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__ConfigRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtEA900II__ConfigRes, config),
    &mt__ea900_ii__config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt__ea900_ii__config_res__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = config */
};
static const ProtobufCIntRange mt__ea900_ii__config_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mt__ea900_ii__config_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_EA900II.ConfigRes",
  "ConfigRes",
  "MtEA900II__ConfigRes",
  "mt_EA900II",
  sizeof(MtEA900II__ConfigRes),
  2,
  mt__ea900_ii__config_res__field_descriptors,
  mt__ea900_ii__config_res__field_indices_by_name,
  1,  mt__ea900_ii__config_res__number_ranges,
  (ProtobufCMessageInit) mt__ea900_ii__config_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor mt__ea900_ii__ea900_iiservice__method_descriptors[3] =
{
  { "GetData", &google__protobuf__empty__descriptor, &mt__ea900_ii__data_res__descriptor },
  { "GetModel", &google__protobuf__empty__descriptor, &mt__ea900_ii__model_res__descriptor },
  { "GetConfig", &google__protobuf__empty__descriptor, &mt__ea900_ii__config_res__descriptor },
};
const unsigned mt__ea900_ii__ea900_iiservice__method_indices_by_name[] = {
  2,        /* GetConfig */
  0,        /* GetData */
  1         /* GetModel */
};
const ProtobufCServiceDescriptor mt__ea900_ii__ea900_iiservice__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "mt_EA900II.EA900IIService",
  "EA900IIService",
  "MtEA900II__EA900IIService",
  "mt_EA900II",
  3,
  mt__ea900_ii__ea900_iiservice__method_descriptors,
  mt__ea900_ii__ea900_iiservice__method_indices_by_name
};
void mt__ea900_ii__ea900_iiservice__get_data(ProtobufCService *service,
                                             const Google__Protobuf__Empty *input,
                                             MtEA900II__DataRes_Closure closure,
                                             void *closure_data)
{
  assert(service->descriptor == &mt__ea900_ii__ea900_iiservice__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt__ea900_ii__ea900_iiservice__get_model(ProtobufCService *service,
                                              const Google__Protobuf__Empty *input,
                                              MtEA900II__ModelRes_Closure closure,
                                              void *closure_data)
{
  assert(service->descriptor == &mt__ea900_ii__ea900_iiservice__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt__ea900_ii__ea900_iiservice__get_config(ProtobufCService *service,
                                               const Google__Protobuf__Empty *input,
                                               MtEA900II__ConfigRes_Closure closure,
                                               void *closure_data)
{
  assert(service->descriptor == &mt__ea900_ii__ea900_iiservice__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt__ea900_ii__ea900_iiservice__init (MtEA900II__EA900IIService_Service *service,
                                          MtEA900II__EA900IIService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &mt__ea900_ii__ea900_iiservice__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
