/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mt_proto_PRS3342AF.proto */

#ifndef PROTOBUF_C_mt_5fproto_5fPRS3342AF_2eproto__INCLUDED
#define PROTOBUF_C_mt_5fproto_5fPRS3342AF_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/empty.pb-c.h"

typedef struct _Data Data;
typedef struct _DatasRes DatasRes;
typedef struct _State State;
typedef struct _StatesRes StatesRes;


/* --- enums --- */


/* --- messages --- */

struct  _Data
{
  ProtobufCMessage base;
  /*
   * 名称
   */
  char *name;
  /*
   * 值
   */
  float value;
};
#define DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _DatasRes
{
  ProtobufCMessage base;
  int32_t rescode;
  size_t n_datas;
  Data **datas;
};
#define DATAS_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&datas_res__descriptor) \
    , 0, 0,NULL }


struct  _State
{
  ProtobufCMessage base;
  char *name;
  protobuf_c_boolean value;
};
#define STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&state__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _StatesRes
{
  ProtobufCMessage base;
  int32_t rescode;
  size_t n_states;
  State **states;
};
#define STATES_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&states_res__descriptor) \
    , 0, 0,NULL }


/* Data methods */
void   data__init
                     (Data         *message);
size_t data__get_packed_size
                     (const Data   *message);
size_t data__pack
                     (const Data   *message,
                      uint8_t             *out);
size_t data__pack_to_buffer
                     (const Data   *message,
                      ProtobufCBuffer     *buffer);
Data *
       data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data__free_unpacked
                     (Data *message,
                      ProtobufCAllocator *allocator);
/* DatasRes methods */
void   datas_res__init
                     (DatasRes         *message);
size_t datas_res__get_packed_size
                     (const DatasRes   *message);
size_t datas_res__pack
                     (const DatasRes   *message,
                      uint8_t             *out);
size_t datas_res__pack_to_buffer
                     (const DatasRes   *message,
                      ProtobufCBuffer     *buffer);
DatasRes *
       datas_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   datas_res__free_unpacked
                     (DatasRes *message,
                      ProtobufCAllocator *allocator);
/* State methods */
void   state__init
                     (State         *message);
size_t state__get_packed_size
                     (const State   *message);
size_t state__pack
                     (const State   *message,
                      uint8_t             *out);
size_t state__pack_to_buffer
                     (const State   *message,
                      ProtobufCBuffer     *buffer);
State *
       state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   state__free_unpacked
                     (State *message,
                      ProtobufCAllocator *allocator);
/* StatesRes methods */
void   states_res__init
                     (StatesRes         *message);
size_t states_res__get_packed_size
                     (const StatesRes   *message);
size_t states_res__pack
                     (const StatesRes   *message,
                      uint8_t             *out);
size_t states_res__pack_to_buffer
                     (const StatesRes   *message,
                      ProtobufCBuffer     *buffer);
StatesRes *
       states_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   states_res__free_unpacked
                     (StatesRes *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Data_Closure)
                 (const Data *message,
                  void *closure_data);
typedef void (*DatasRes_Closure)
                 (const DatasRes *message,
                  void *closure_data);
typedef void (*State_Closure)
                 (const State *message,
                  void *closure_data);
typedef void (*StatesRes_Closure)
                 (const StatesRes *message,
                  void *closure_data);

/* --- services --- */

typedef struct _PRS3342AFService_Service PRS3342AFService_Service;
struct _PRS3342AFService_Service
{
  ProtobufCService base;
  void (*get_datas)(PRS3342AFService_Service *service,
                    const Google__Protobuf__Empty *input,
                    DatasRes_Closure closure,
                    void *closure_data);
  void (*get_states)(PRS3342AFService_Service *service,
                     const Google__Protobuf__Empty *input,
                     StatesRes_Closure closure,
                     void *closure_data);
};
typedef void (*PRS3342AFService_ServiceDestroy)(PRS3342AFService_Service *);
void prs3342_afservice__init (PRS3342AFService_Service *service,
                              PRS3342AFService_ServiceDestroy destroy);
#define PRS3342_AFSERVICE__BASE_INIT \
    { &prs3342_afservice__descriptor, protobuf_c_service_invoke_internal, NULL }
#define PRS3342_AFSERVICE__INIT(function_prefix__) \
    { PRS3342_AFSERVICE__BASE_INIT,\
      function_prefix__ ## get_datas,\
      function_prefix__ ## get_states  }
void prs3342_afservice__get_datas(ProtobufCService *service,
                                  const Google__Protobuf__Empty *input,
                                  DatasRes_Closure closure,
                                  void *closure_data);
void prs3342_afservice__get_states(ProtobufCService *service,
                                   const Google__Protobuf__Empty *input,
                                   StatesRes_Closure closure,
                                   void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor data__descriptor;
extern const ProtobufCMessageDescriptor datas_res__descriptor;
extern const ProtobufCMessageDescriptor state__descriptor;
extern const ProtobufCMessageDescriptor states_res__descriptor;
extern const ProtobufCServiceDescriptor prs3342_afservice__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_mt_5fproto_5fPRS3342AF_2eproto__INCLUDED */
