/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mt_proto_PRS3342AF.proto */

#ifndef PROTOBUF_C_mt_5fproto_5fPRS3342AF_2eproto__INCLUDED
#define PROTOBUF_C_mt_5fproto_5fPRS3342AF_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/empty.pb-c.h"

typedef struct _MtPrs3342__Data MtPrs3342__Data;
typedef struct _MtPrs3342__DatasRes MtPrs3342__DatasRes;
typedef struct _MtPrs3342__State MtPrs3342__State;
typedef struct _MtPrs3342__StatesRes MtPrs3342__StatesRes;


/* --- enums --- */


/* --- messages --- */

struct  _MtPrs3342__Data
{
  ProtobufCMessage base;
  /*
   * 名称
   */
  char *name;
  /*
   * 值
   */
  float value;
};
#define MT_PRS3342__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_prs3342__data__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _MtPrs3342__DatasRes
{
  ProtobufCMessage base;
  int32_t rescode;
  size_t n_datas;
  MtPrs3342__Data **datas;
};
#define MT_PRS3342__DATAS_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_prs3342__datas_res__descriptor) \
    , 0, 0,NULL }


struct  _MtPrs3342__State
{
  ProtobufCMessage base;
  char *name;
  protobuf_c_boolean value;
};
#define MT_PRS3342__STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_prs3342__state__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _MtPrs3342__StatesRes
{
  ProtobufCMessage base;
  int32_t rescode;
  size_t n_states;
  MtPrs3342__State **states;
};
#define MT_PRS3342__STATES_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_prs3342__states_res__descriptor) \
    , 0, 0,NULL }


/* MtPrs3342__Data methods */
void   mt_prs3342__data__init
                     (MtPrs3342__Data         *message);
size_t mt_prs3342__data__get_packed_size
                     (const MtPrs3342__Data   *message);
size_t mt_prs3342__data__pack
                     (const MtPrs3342__Data   *message,
                      uint8_t             *out);
size_t mt_prs3342__data__pack_to_buffer
                     (const MtPrs3342__Data   *message,
                      ProtobufCBuffer     *buffer);
MtPrs3342__Data *
       mt_prs3342__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_prs3342__data__free_unpacked
                     (MtPrs3342__Data *message,
                      ProtobufCAllocator *allocator);
/* MtPrs3342__DatasRes methods */
void   mt_prs3342__datas_res__init
                     (MtPrs3342__DatasRes         *message);
size_t mt_prs3342__datas_res__get_packed_size
                     (const MtPrs3342__DatasRes   *message);
size_t mt_prs3342__datas_res__pack
                     (const MtPrs3342__DatasRes   *message,
                      uint8_t             *out);
size_t mt_prs3342__datas_res__pack_to_buffer
                     (const MtPrs3342__DatasRes   *message,
                      ProtobufCBuffer     *buffer);
MtPrs3342__DatasRes *
       mt_prs3342__datas_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_prs3342__datas_res__free_unpacked
                     (MtPrs3342__DatasRes *message,
                      ProtobufCAllocator *allocator);
/* MtPrs3342__State methods */
void   mt_prs3342__state__init
                     (MtPrs3342__State         *message);
size_t mt_prs3342__state__get_packed_size
                     (const MtPrs3342__State   *message);
size_t mt_prs3342__state__pack
                     (const MtPrs3342__State   *message,
                      uint8_t             *out);
size_t mt_prs3342__state__pack_to_buffer
                     (const MtPrs3342__State   *message,
                      ProtobufCBuffer     *buffer);
MtPrs3342__State *
       mt_prs3342__state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_prs3342__state__free_unpacked
                     (MtPrs3342__State *message,
                      ProtobufCAllocator *allocator);
/* MtPrs3342__StatesRes methods */
void   mt_prs3342__states_res__init
                     (MtPrs3342__StatesRes         *message);
size_t mt_prs3342__states_res__get_packed_size
                     (const MtPrs3342__StatesRes   *message);
size_t mt_prs3342__states_res__pack
                     (const MtPrs3342__StatesRes   *message,
                      uint8_t             *out);
size_t mt_prs3342__states_res__pack_to_buffer
                     (const MtPrs3342__StatesRes   *message,
                      ProtobufCBuffer     *buffer);
MtPrs3342__StatesRes *
       mt_prs3342__states_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_prs3342__states_res__free_unpacked
                     (MtPrs3342__StatesRes *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MtPrs3342__Data_Closure)
                 (const MtPrs3342__Data *message,
                  void *closure_data);
typedef void (*MtPrs3342__DatasRes_Closure)
                 (const MtPrs3342__DatasRes *message,
                  void *closure_data);
typedef void (*MtPrs3342__State_Closure)
                 (const MtPrs3342__State *message,
                  void *closure_data);
typedef void (*MtPrs3342__StatesRes_Closure)
                 (const MtPrs3342__StatesRes *message,
                  void *closure_data);

/* --- services --- */

typedef struct _MtPrs3342__PRS3342AFService_Service MtPrs3342__PRS3342AFService_Service;
struct _MtPrs3342__PRS3342AFService_Service
{
  ProtobufCService base;
  void (*get_datas)(MtPrs3342__PRS3342AFService_Service *service,
                    const Google__Protobuf__Empty *input,
                    MtPrs3342__DatasRes_Closure closure,
                    void *closure_data);
  void (*get_states)(MtPrs3342__PRS3342AFService_Service *service,
                     const Google__Protobuf__Empty *input,
                     MtPrs3342__StatesRes_Closure closure,
                     void *closure_data);
};
typedef void (*MtPrs3342__PRS3342AFService_ServiceDestroy)(MtPrs3342__PRS3342AFService_Service *);
void mt_prs3342__prs3342_afservice__init (MtPrs3342__PRS3342AFService_Service *service,
                                          MtPrs3342__PRS3342AFService_ServiceDestroy destroy);
#define MT_PRS3342__PRS3342_AFSERVICE__BASE_INIT \
    { &mt_prs3342__prs3342_afservice__descriptor, protobuf_c_service_invoke_internal, NULL }
#define MT_PRS3342__PRS3342_AFSERVICE__INIT(function_prefix__) \
    { MT_PRS3342__PRS3342_AFSERVICE__BASE_INIT,\
      function_prefix__ ## get_datas,\
      function_prefix__ ## get_states  }
void mt_prs3342__prs3342_afservice__get_datas(ProtobufCService *service,
                                              const Google__Protobuf__Empty *input,
                                              MtPrs3342__DatasRes_Closure closure,
                                              void *closure_data);
void mt_prs3342__prs3342_afservice__get_states(ProtobufCService *service,
                                               const Google__Protobuf__Empty *input,
                                               MtPrs3342__StatesRes_Closure closure,
                                               void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mt_prs3342__data__descriptor;
extern const ProtobufCMessageDescriptor mt_prs3342__datas_res__descriptor;
extern const ProtobufCMessageDescriptor mt_prs3342__state__descriptor;
extern const ProtobufCMessageDescriptor mt_prs3342__states_res__descriptor;
extern const ProtobufCServiceDescriptor mt_prs3342__prs3342_afservice__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_mt_5fproto_5fPRS3342AF_2eproto__INCLUDED */
