/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mt_proto_pulse_motor.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mt_proto_pulse_motor.pb-c.h"
void   mt_pulse_motor__set_state_req__init
                     (MtPulseMotor__SetStateReq         *message)
{
  static const MtPulseMotor__SetStateReq init_value = MT_PULSE_MOTOR__SET_STATE_REQ__INIT;
  *message = init_value;
}
size_t mt_pulse_motor__set_state_req__get_packed_size
                     (const MtPulseMotor__SetStateReq *message)
{
  assert(message->base.descriptor == &mt_pulse_motor__set_state_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_pulse_motor__set_state_req__pack
                     (const MtPulseMotor__SetStateReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_pulse_motor__set_state_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_pulse_motor__set_state_req__pack_to_buffer
                     (const MtPulseMotor__SetStateReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_pulse_motor__set_state_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtPulseMotor__SetStateReq *
       mt_pulse_motor__set_state_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtPulseMotor__SetStateReq *)
     protobuf_c_message_unpack (&mt_pulse_motor__set_state_req__descriptor,
                                allocator, len, data);
}
void   mt_pulse_motor__set_state_req__free_unpacked
                     (MtPulseMotor__SetStateReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_pulse_motor__set_state_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_pulse_motor__set_state_res__init
                     (MtPulseMotor__SetStateRes         *message)
{
  static const MtPulseMotor__SetStateRes init_value = MT_PULSE_MOTOR__SET_STATE_RES__INIT;
  *message = init_value;
}
size_t mt_pulse_motor__set_state_res__get_packed_size
                     (const MtPulseMotor__SetStateRes *message)
{
  assert(message->base.descriptor == &mt_pulse_motor__set_state_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_pulse_motor__set_state_res__pack
                     (const MtPulseMotor__SetStateRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_pulse_motor__set_state_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_pulse_motor__set_state_res__pack_to_buffer
                     (const MtPulseMotor__SetStateRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_pulse_motor__set_state_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtPulseMotor__SetStateRes *
       mt_pulse_motor__set_state_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtPulseMotor__SetStateRes *)
     protobuf_c_message_unpack (&mt_pulse_motor__set_state_res__descriptor,
                                allocator, len, data);
}
void   mt_pulse_motor__set_state_res__free_unpacked
                     (MtPulseMotor__SetStateRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_pulse_motor__set_state_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_pulse_motor__get_state_res__init
                     (MtPulseMotor__GetStateRes         *message)
{
  static const MtPulseMotor__GetStateRes init_value = MT_PULSE_MOTOR__GET_STATE_RES__INIT;
  *message = init_value;
}
size_t mt_pulse_motor__get_state_res__get_packed_size
                     (const MtPulseMotor__GetStateRes *message)
{
  assert(message->base.descriptor == &mt_pulse_motor__get_state_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_pulse_motor__get_state_res__pack
                     (const MtPulseMotor__GetStateRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_pulse_motor__get_state_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_pulse_motor__get_state_res__pack_to_buffer
                     (const MtPulseMotor__GetStateRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_pulse_motor__get_state_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtPulseMotor__GetStateRes *
       mt_pulse_motor__get_state_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtPulseMotor__GetStateRes *)
     protobuf_c_message_unpack (&mt_pulse_motor__get_state_res__descriptor,
                                allocator, len, data);
}
void   mt_pulse_motor__get_state_res__free_unpacked
                     (MtPulseMotor__GetStateRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_pulse_motor__get_state_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_pulse_motor__set_state_with_delay_req__init
                     (MtPulseMotor__SetStateWithDelayReq         *message)
{
  static const MtPulseMotor__SetStateWithDelayReq init_value = MT_PULSE_MOTOR__SET_STATE_WITH_DELAY_REQ__INIT;
  *message = init_value;
}
size_t mt_pulse_motor__set_state_with_delay_req__get_packed_size
                     (const MtPulseMotor__SetStateWithDelayReq *message)
{
  assert(message->base.descriptor == &mt_pulse_motor__set_state_with_delay_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_pulse_motor__set_state_with_delay_req__pack
                     (const MtPulseMotor__SetStateWithDelayReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_pulse_motor__set_state_with_delay_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_pulse_motor__set_state_with_delay_req__pack_to_buffer
                     (const MtPulseMotor__SetStateWithDelayReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_pulse_motor__set_state_with_delay_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtPulseMotor__SetStateWithDelayReq *
       mt_pulse_motor__set_state_with_delay_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtPulseMotor__SetStateWithDelayReq *)
     protobuf_c_message_unpack (&mt_pulse_motor__set_state_with_delay_req__descriptor,
                                allocator, len, data);
}
void   mt_pulse_motor__set_state_with_delay_req__free_unpacked
                     (MtPulseMotor__SetStateWithDelayReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_pulse_motor__set_state_with_delay_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_pulse_motor__set_state_with_delay_res__init
                     (MtPulseMotor__SetStateWithDelayRes         *message)
{
  static const MtPulseMotor__SetStateWithDelayRes init_value = MT_PULSE_MOTOR__SET_STATE_WITH_DELAY_RES__INIT;
  *message = init_value;
}
size_t mt_pulse_motor__set_state_with_delay_res__get_packed_size
                     (const MtPulseMotor__SetStateWithDelayRes *message)
{
  assert(message->base.descriptor == &mt_pulse_motor__set_state_with_delay_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_pulse_motor__set_state_with_delay_res__pack
                     (const MtPulseMotor__SetStateWithDelayRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_pulse_motor__set_state_with_delay_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_pulse_motor__set_state_with_delay_res__pack_to_buffer
                     (const MtPulseMotor__SetStateWithDelayRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_pulse_motor__set_state_with_delay_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtPulseMotor__SetStateWithDelayRes *
       mt_pulse_motor__set_state_with_delay_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtPulseMotor__SetStateWithDelayRes *)
     protobuf_c_message_unpack (&mt_pulse_motor__set_state_with_delay_res__descriptor,
                                allocator, len, data);
}
void   mt_pulse_motor__set_state_with_delay_res__free_unpacked
                     (MtPulseMotor__SetStateWithDelayRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_pulse_motor__set_state_with_delay_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mt_pulse_motor__set_state_req__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtPulseMotor__SetStateReq, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_pulse_motor__set_state_req__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange mt_pulse_motor__set_state_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_pulse_motor__set_state_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_pulse_motor.SetStateReq",
  "SetStateReq",
  "MtPulseMotor__SetStateReq",
  "mt_pulse_motor",
  sizeof(MtPulseMotor__SetStateReq),
  1,
  mt_pulse_motor__set_state_req__field_descriptors,
  mt_pulse_motor__set_state_req__field_indices_by_name,
  1,  mt_pulse_motor__set_state_req__number_ranges,
  (ProtobufCMessageInit) mt_pulse_motor__set_state_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_pulse_motor__set_state_res__field_descriptors[1] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtPulseMotor__SetStateRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_pulse_motor__set_state_res__field_indices_by_name[] = {
  0,   /* field[0] = code */
};
static const ProtobufCIntRange mt_pulse_motor__set_state_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_pulse_motor__set_state_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_pulse_motor.SetStateRes",
  "SetStateRes",
  "MtPulseMotor__SetStateRes",
  "mt_pulse_motor",
  sizeof(MtPulseMotor__SetStateRes),
  1,
  mt_pulse_motor__set_state_res__field_descriptors,
  mt_pulse_motor__set_state_res__field_indices_by_name,
  1,  mt_pulse_motor__set_state_res__number_ranges,
  (ProtobufCMessageInit) mt_pulse_motor__set_state_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_pulse_motor__get_state_res__field_descriptors[3] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtPulseMotor__GetStateRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtPulseMotor__GetStateRes, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lefttime",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtPulseMotor__GetStateRes, lefttime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_pulse_motor__get_state_res__field_indices_by_name[] = {
  0,   /* field[0] = code */
  2,   /* field[2] = lefttime */
  1,   /* field[1] = state */
};
static const ProtobufCIntRange mt_pulse_motor__get_state_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mt_pulse_motor__get_state_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_pulse_motor.GetStateRes",
  "GetStateRes",
  "MtPulseMotor__GetStateRes",
  "mt_pulse_motor",
  sizeof(MtPulseMotor__GetStateRes),
  3,
  mt_pulse_motor__get_state_res__field_descriptors,
  mt_pulse_motor__get_state_res__field_indices_by_name,
  1,  mt_pulse_motor__get_state_res__number_ranges,
  (ProtobufCMessageInit) mt_pulse_motor__get_state_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_pulse_motor__set_state_with_delay_req__field_descriptors[2] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtPulseMotor__SetStateWithDelayReq, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtPulseMotor__SetStateWithDelayReq, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_pulse_motor__set_state_with_delay_req__field_indices_by_name[] = {
  0,   /* field[0] = state */
  1,   /* field[1] = time */
};
static const ProtobufCIntRange mt_pulse_motor__set_state_with_delay_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mt_pulse_motor__set_state_with_delay_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_pulse_motor.SetStateWithDelayReq",
  "SetStateWithDelayReq",
  "MtPulseMotor__SetStateWithDelayReq",
  "mt_pulse_motor",
  sizeof(MtPulseMotor__SetStateWithDelayReq),
  2,
  mt_pulse_motor__set_state_with_delay_req__field_descriptors,
  mt_pulse_motor__set_state_with_delay_req__field_indices_by_name,
  1,  mt_pulse_motor__set_state_with_delay_req__number_ranges,
  (ProtobufCMessageInit) mt_pulse_motor__set_state_with_delay_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_pulse_motor__set_state_with_delay_res__field_descriptors[1] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtPulseMotor__SetStateWithDelayRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_pulse_motor__set_state_with_delay_res__field_indices_by_name[] = {
  0,   /* field[0] = code */
};
static const ProtobufCIntRange mt_pulse_motor__set_state_with_delay_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_pulse_motor__set_state_with_delay_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_pulse_motor.SetStateWithDelayRes",
  "SetStateWithDelayRes",
  "MtPulseMotor__SetStateWithDelayRes",
  "mt_pulse_motor",
  sizeof(MtPulseMotor__SetStateWithDelayRes),
  1,
  mt_pulse_motor__set_state_with_delay_res__field_descriptors,
  mt_pulse_motor__set_state_with_delay_res__field_indices_by_name,
  1,  mt_pulse_motor__set_state_with_delay_res__number_ranges,
  (ProtobufCMessageInit) mt_pulse_motor__set_state_with_delay_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor mt_pulse_motor__pulse_motor_service__method_descriptors[3] =
{
  { "SetState", &mt_pulse_motor__set_state_req__descriptor, &mt_pulse_motor__set_state_res__descriptor },
  { "GetState", &google__protobuf__empty__descriptor, &mt_pulse_motor__get_state_res__descriptor },
  { "SetStateWithDelay", &mt_pulse_motor__set_state_with_delay_req__descriptor, &mt_pulse_motor__set_state_with_delay_res__descriptor },
};
const unsigned mt_pulse_motor__pulse_motor_service__method_indices_by_name[] = {
  1,        /* GetState */
  0,        /* SetState */
  2         /* SetStateWithDelay */
};
const ProtobufCServiceDescriptor mt_pulse_motor__pulse_motor_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "mt_pulse_motor.PulseMotorService",
  "PulseMotorService",
  "MtPulseMotor__PulseMotorService",
  "mt_pulse_motor",
  3,
  mt_pulse_motor__pulse_motor_service__method_descriptors,
  mt_pulse_motor__pulse_motor_service__method_indices_by_name
};
void mt_pulse_motor__pulse_motor_service__set_state(ProtobufCService *service,
                                                    const MtPulseMotor__SetStateReq *input,
                                                    MtPulseMotor__SetStateRes_Closure closure,
                                                    void *closure_data)
{
  assert(service->descriptor == &mt_pulse_motor__pulse_motor_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_pulse_motor__pulse_motor_service__get_state(ProtobufCService *service,
                                                    const Google__Protobuf__Empty *input,
                                                    MtPulseMotor__GetStateRes_Closure closure,
                                                    void *closure_data)
{
  assert(service->descriptor == &mt_pulse_motor__pulse_motor_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_pulse_motor__pulse_motor_service__set_state_with_delay(ProtobufCService *service,
                                                               const MtPulseMotor__SetStateWithDelayReq *input,
                                                               MtPulseMotor__SetStateWithDelayRes_Closure closure,
                                                               void *closure_data)
{
  assert(service->descriptor == &mt_pulse_motor__pulse_motor_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_pulse_motor__pulse_motor_service__init (MtPulseMotor__PulseMotorService_Service *service,
                                                MtPulseMotor__PulseMotorService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &mt_pulse_motor__pulse_motor_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
