/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mt_proto_EA900II.proto */

#ifndef PROTOBUF_C_mt_5fproto_5fEA900II_2eproto__INCLUDED
#define PROTOBUF_C_mt_5fproto_5fEA900II_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/empty.pb-c.h"

typedef struct _MtEA900II__Data MtEA900II__Data;
typedef struct _MtEA900II__Model MtEA900II__Model;
typedef struct _MtEA900II__Config MtEA900II__Config;
typedef struct _MtEA900II__DataRes MtEA900II__DataRes;
typedef struct _MtEA900II__ModelRes MtEA900II__ModelRes;
typedef struct _MtEA900II__ConfigRes MtEA900II__ConfigRes;


/* --- enums --- */


/* --- messages --- */

struct  _MtEA900II__Data
{
  ProtobufCMessage base;
  /*
   * 输入电压
   */
  float votagein;
  /*
   * 输出电压
   */
  float votageout;
  /*
   * 输出负载百分比
   */
  float loadpercent;
  /*
   * 输入电源频率
   */
  float freqin;
  /*
   * 电池电压
   */
  float votagebat;
  /*
   * 电池温度
   */
  float temp;
  /*
   * 市电故障 true:故障 false:正常
   */
  protobuf_c_boolean w7;
  /*
   * 电池电压低 true:电压低 false:正常
   */
  protobuf_c_boolean w6;
  /*
   * 旁路/逆变状态 true:旁路 false:逆变
   */
  protobuf_c_boolean w5;
  /*
   * UPS故障 true:故障 false:正常
   */
  protobuf_c_boolean w4;
  /*
   * UPS类型 true:后备机 false:在线机
   */
  protobuf_c_boolean w3;
  /*
   * 系统测试状态 true:测试中 false:无
   */
  protobuf_c_boolean w2;
  /*
   * 系统关机状态 true:关机激活 false:无
   */
  protobuf_c_boolean w1;
  /*
   * 告警音 true:开启 false:关闭
   */
  protobuf_c_boolean w0;
};
#define MT__EA900_II__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt__ea900_ii__data__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  _MtEA900II__Model
{
  ProtobufCMessage base;
  /*
   * ups公司名称
   */
  char *name;
  /*
   * UPS型号
   */
  char *model;
  /*
   * UPS版本
   */
  char *version;
};
#define MT__EA900_II__MODEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt__ea900_ii__model__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _MtEA900II__Config
{
  ProtobufCMessage base;
  /*
   * 额定电压
   */
  float votage;
  /*
   * 额定电流
   */
  float current;
  /*
   * 电池最大电压
   */
  float batvotage;
  /*
   * 额定频率
   */
  float freq;
};
#define MT__EA900_II__CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt__ea900_ii__config__descriptor) \
    , 0, 0, 0, 0 }


struct  _MtEA900II__DataRes
{
  ProtobufCMessage base;
  int32_t code;
  MtEA900II__Data *datas;
};
#define MT__EA900_II__DATA_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt__ea900_ii__data_res__descriptor) \
    , 0, NULL }


struct  _MtEA900II__ModelRes
{
  ProtobufCMessage base;
  int32_t code;
  MtEA900II__Model *model;
};
#define MT__EA900_II__MODEL_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt__ea900_ii__model_res__descriptor) \
    , 0, NULL }


struct  _MtEA900II__ConfigRes
{
  ProtobufCMessage base;
  int32_t code;
  MtEA900II__Config *config;
};
#define MT__EA900_II__CONFIG_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt__ea900_ii__config_res__descriptor) \
    , 0, NULL }


/* MtEA900II__Data methods */
void   mt__ea900_ii__data__init
                     (MtEA900II__Data         *message);
size_t mt__ea900_ii__data__get_packed_size
                     (const MtEA900II__Data   *message);
size_t mt__ea900_ii__data__pack
                     (const MtEA900II__Data   *message,
                      uint8_t             *out);
size_t mt__ea900_ii__data__pack_to_buffer
                     (const MtEA900II__Data   *message,
                      ProtobufCBuffer     *buffer);
MtEA900II__Data *
       mt__ea900_ii__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt__ea900_ii__data__free_unpacked
                     (MtEA900II__Data *message,
                      ProtobufCAllocator *allocator);
/* MtEA900II__Model methods */
void   mt__ea900_ii__model__init
                     (MtEA900II__Model         *message);
size_t mt__ea900_ii__model__get_packed_size
                     (const MtEA900II__Model   *message);
size_t mt__ea900_ii__model__pack
                     (const MtEA900II__Model   *message,
                      uint8_t             *out);
size_t mt__ea900_ii__model__pack_to_buffer
                     (const MtEA900II__Model   *message,
                      ProtobufCBuffer     *buffer);
MtEA900II__Model *
       mt__ea900_ii__model__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt__ea900_ii__model__free_unpacked
                     (MtEA900II__Model *message,
                      ProtobufCAllocator *allocator);
/* MtEA900II__Config methods */
void   mt__ea900_ii__config__init
                     (MtEA900II__Config         *message);
size_t mt__ea900_ii__config__get_packed_size
                     (const MtEA900II__Config   *message);
size_t mt__ea900_ii__config__pack
                     (const MtEA900II__Config   *message,
                      uint8_t             *out);
size_t mt__ea900_ii__config__pack_to_buffer
                     (const MtEA900II__Config   *message,
                      ProtobufCBuffer     *buffer);
MtEA900II__Config *
       mt__ea900_ii__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt__ea900_ii__config__free_unpacked
                     (MtEA900II__Config *message,
                      ProtobufCAllocator *allocator);
/* MtEA900II__DataRes methods */
void   mt__ea900_ii__data_res__init
                     (MtEA900II__DataRes         *message);
size_t mt__ea900_ii__data_res__get_packed_size
                     (const MtEA900II__DataRes   *message);
size_t mt__ea900_ii__data_res__pack
                     (const MtEA900II__DataRes   *message,
                      uint8_t             *out);
size_t mt__ea900_ii__data_res__pack_to_buffer
                     (const MtEA900II__DataRes   *message,
                      ProtobufCBuffer     *buffer);
MtEA900II__DataRes *
       mt__ea900_ii__data_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt__ea900_ii__data_res__free_unpacked
                     (MtEA900II__DataRes *message,
                      ProtobufCAllocator *allocator);
/* MtEA900II__ModelRes methods */
void   mt__ea900_ii__model_res__init
                     (MtEA900II__ModelRes         *message);
size_t mt__ea900_ii__model_res__get_packed_size
                     (const MtEA900II__ModelRes   *message);
size_t mt__ea900_ii__model_res__pack
                     (const MtEA900II__ModelRes   *message,
                      uint8_t             *out);
size_t mt__ea900_ii__model_res__pack_to_buffer
                     (const MtEA900II__ModelRes   *message,
                      ProtobufCBuffer     *buffer);
MtEA900II__ModelRes *
       mt__ea900_ii__model_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt__ea900_ii__model_res__free_unpacked
                     (MtEA900II__ModelRes *message,
                      ProtobufCAllocator *allocator);
/* MtEA900II__ConfigRes methods */
void   mt__ea900_ii__config_res__init
                     (MtEA900II__ConfigRes         *message);
size_t mt__ea900_ii__config_res__get_packed_size
                     (const MtEA900II__ConfigRes   *message);
size_t mt__ea900_ii__config_res__pack
                     (const MtEA900II__ConfigRes   *message,
                      uint8_t             *out);
size_t mt__ea900_ii__config_res__pack_to_buffer
                     (const MtEA900II__ConfigRes   *message,
                      ProtobufCBuffer     *buffer);
MtEA900II__ConfigRes *
       mt__ea900_ii__config_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt__ea900_ii__config_res__free_unpacked
                     (MtEA900II__ConfigRes *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MtEA900II__Data_Closure)
                 (const MtEA900II__Data *message,
                  void *closure_data);
typedef void (*MtEA900II__Model_Closure)
                 (const MtEA900II__Model *message,
                  void *closure_data);
typedef void (*MtEA900II__Config_Closure)
                 (const MtEA900II__Config *message,
                  void *closure_data);
typedef void (*MtEA900II__DataRes_Closure)
                 (const MtEA900II__DataRes *message,
                  void *closure_data);
typedef void (*MtEA900II__ModelRes_Closure)
                 (const MtEA900II__ModelRes *message,
                  void *closure_data);
typedef void (*MtEA900II__ConfigRes_Closure)
                 (const MtEA900II__ConfigRes *message,
                  void *closure_data);

/* --- services --- */

typedef struct _MtEA900II__EA900IIService_Service MtEA900II__EA900IIService_Service;
struct _MtEA900II__EA900IIService_Service
{
  ProtobufCService base;
  void (*get_data)(MtEA900II__EA900IIService_Service *service,
                   const Google__Protobuf__Empty *input,
                   MtEA900II__DataRes_Closure closure,
                   void *closure_data);
  void (*get_model)(MtEA900II__EA900IIService_Service *service,
                    const Google__Protobuf__Empty *input,
                    MtEA900II__ModelRes_Closure closure,
                    void *closure_data);
  void (*get_config)(MtEA900II__EA900IIService_Service *service,
                     const Google__Protobuf__Empty *input,
                     MtEA900II__ConfigRes_Closure closure,
                     void *closure_data);
};
typedef void (*MtEA900II__EA900IIService_ServiceDestroy)(MtEA900II__EA900IIService_Service *);
void mt__ea900_ii__ea900_iiservice__init (MtEA900II__EA900IIService_Service *service,
                                          MtEA900II__EA900IIService_ServiceDestroy destroy);
#define MT__EA900_II__EA900_IISERVICE__BASE_INIT \
    { &mt__ea900_ii__ea900_iiservice__descriptor, protobuf_c_service_invoke_internal, NULL }
#define MT__EA900_II__EA900_IISERVICE__INIT(function_prefix__) \
    { MT__EA900_II__EA900_IISERVICE__BASE_INIT,\
      function_prefix__ ## get_data,\
      function_prefix__ ## get_model,\
      function_prefix__ ## get_config  }
void mt__ea900_ii__ea900_iiservice__get_data(ProtobufCService *service,
                                             const Google__Protobuf__Empty *input,
                                             MtEA900II__DataRes_Closure closure,
                                             void *closure_data);
void mt__ea900_ii__ea900_iiservice__get_model(ProtobufCService *service,
                                              const Google__Protobuf__Empty *input,
                                              MtEA900II__ModelRes_Closure closure,
                                              void *closure_data);
void mt__ea900_ii__ea900_iiservice__get_config(ProtobufCService *service,
                                               const Google__Protobuf__Empty *input,
                                               MtEA900II__ConfigRes_Closure closure,
                                               void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mt__ea900_ii__data__descriptor;
extern const ProtobufCMessageDescriptor mt__ea900_ii__model__descriptor;
extern const ProtobufCMessageDescriptor mt__ea900_ii__config__descriptor;
extern const ProtobufCMessageDescriptor mt__ea900_ii__data_res__descriptor;
extern const ProtobufCMessageDescriptor mt__ea900_ii__model_res__descriptor;
extern const ProtobufCMessageDescriptor mt__ea900_ii__config_res__descriptor;
extern const ProtobufCServiceDescriptor mt__ea900_ii__ea900_iiservice__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_mt_5fproto_5fEA900II_2eproto__INCLUDED */
