/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mt_proto_EA900II.proto */

#ifndef PROTOBUF_C_mt_5fproto_5fEA900II_2eproto__INCLUDED
#define PROTOBUF_C_mt_5fproto_5fEA900II_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/empty.pb-c.h"

typedef struct _Data Data;
typedef struct _DataRes DataRes;


/* --- enums --- */


/* --- messages --- */

struct  _Data
{
  ProtobufCMessage base;
  /*
   * 输入电压
   */
  float votagein;
  /*
   * 输出电压
   */
  float votageout;
  /*
   * 输出负载百分比
   */
  float loadpercent;
  /*
   * 输入电源频率
   */
  float freqin;
  /*
   * 电池电压
   */
  float votagebat;
  /*
   * 电池温度
   */
  float temp;
  /*
   * 市电故障 true:故障 false:正常
   */
  protobuf_c_boolean w7;
  /*
   * 电池电压低 true:电压低 false:正常
   */
  protobuf_c_boolean w6;
  /*
   * 旁路/逆变状态 true:旁路 false:逆变
   */
  protobuf_c_boolean w5;
  /*
   * UPS故障 true:故障 false:正常
   */
  protobuf_c_boolean w4;
  /*
   * UPS类型 true:后备机 false:在线机
   */
  protobuf_c_boolean w3;
  /*
   * 系统测试状态 true:测试中 false:无
   */
  protobuf_c_boolean w2;
  /*
   * 系统关机状态 true:关机激活 false:无
   */
  protobuf_c_boolean w1;
  /*
   * 告警音 true:开启 false:关闭
   */
  protobuf_c_boolean w0;
};
#define DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  _DataRes
{
  ProtobufCMessage base;
  int32_t rescode;
  Data *datas;
};
#define DATA_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data_res__descriptor) \
    , 0, NULL }


/* Data methods */
void   data__init
                     (Data         *message);
size_t data__get_packed_size
                     (const Data   *message);
size_t data__pack
                     (const Data   *message,
                      uint8_t             *out);
size_t data__pack_to_buffer
                     (const Data   *message,
                      ProtobufCBuffer     *buffer);
Data *
       data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data__free_unpacked
                     (Data *message,
                      ProtobufCAllocator *allocator);
/* DataRes methods */
void   data_res__init
                     (DataRes         *message);
size_t data_res__get_packed_size
                     (const DataRes   *message);
size_t data_res__pack
                     (const DataRes   *message,
                      uint8_t             *out);
size_t data_res__pack_to_buffer
                     (const DataRes   *message,
                      ProtobufCBuffer     *buffer);
DataRes *
       data_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data_res__free_unpacked
                     (DataRes *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Data_Closure)
                 (const Data *message,
                  void *closure_data);
typedef void (*DataRes_Closure)
                 (const DataRes *message,
                  void *closure_data);

/* --- services --- */

typedef struct _EA900IIService_Service EA900IIService_Service;
struct _EA900IIService_Service
{
  ProtobufCService base;
  void (*get_data)(EA900IIService_Service *service,
                   const Google__Protobuf__Empty *input,
                   DataRes_Closure closure,
                   void *closure_data);
};
typedef void (*EA900IIService_ServiceDestroy)(EA900IIService_Service *);
void ea900_iiservice__init (EA900IIService_Service *service,
                            EA900IIService_ServiceDestroy destroy);
#define EA900_IISERVICE__BASE_INIT \
    { &ea900_iiservice__descriptor, protobuf_c_service_invoke_internal, NULL }
#define EA900_IISERVICE__INIT(function_prefix__) \
    { EA900_IISERVICE__BASE_INIT,\
      function_prefix__ ## get_data  }
void ea900_iiservice__get_data(ProtobufCService *service,
                               const Google__Protobuf__Empty *input,
                               DataRes_Closure closure,
                               void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor data__descriptor;
extern const ProtobufCMessageDescriptor data_res__descriptor;
extern const ProtobufCServiceDescriptor ea900_iiservice__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_mt_5fproto_5fEA900II_2eproto__INCLUDED */
