/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mt_proto_ld100.proto */

#ifndef PROTOBUF_C_mt_5fproto_5fld100_2eproto__INCLUDED
#define PROTOBUF_C_mt_5fproto_5fld100_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MtLd100__GetAddrReq MtLd100__GetAddrReq;
typedef struct _MtLd100__GetAddrRes MtLd100__GetAddrRes;
typedef struct _MtLd100__SetAddrReq MtLd100__SetAddrReq;
typedef struct _MtLd100__SetAddrRes MtLd100__SetAddrRes;
typedef struct _MtLd100__State MtLd100__State;
typedef struct _MtLd100__GetStateReq MtLd100__GetStateReq;
typedef struct _MtLd100__GetStateRes MtLd100__GetStateRes;
typedef struct _MtLd100__GetRelayReq MtLd100__GetRelayReq;
typedef struct _MtLd100__GetRelayRes MtLd100__GetRelayRes;
typedef struct _MtLd100__SetRelayReq MtLd100__SetRelayReq;
typedef struct _MtLd100__SetRelayRes MtLd100__SetRelayRes;


/* --- enums --- */


/* --- messages --- */

struct  _MtLd100__GetAddrReq
{
  ProtobufCMessage base;
  int32_t addr;
};
#define MT_LD100__GET_ADDR_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_ld100__get_addr_req__descriptor) \
    , 0 }


struct  _MtLd100__GetAddrRes
{
  ProtobufCMessage base;
  int32_t rescode;
  int32_t addr;
  protobuf_c_boolean state;
};
#define MT_LD100__GET_ADDR_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_ld100__get_addr_res__descriptor) \
    , 0, 0, 0 }


struct  _MtLd100__SetAddrReq
{
  ProtobufCMessage base;
  int32_t addr;
};
#define MT_LD100__SET_ADDR_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_ld100__set_addr_req__descriptor) \
    , 0 }


struct  _MtLd100__SetAddrRes
{
  ProtobufCMessage base;
  int32_t rescode;
};
#define MT_LD100__SET_ADDR_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_ld100__set_addr_res__descriptor) \
    , 0 }


/*
 * also use in flow f1
 */
struct  _MtLd100__State
{
  ProtobufCMessage base;
  /*
   * 水浸状态, true:正常, false:进水
   */
  protobuf_c_boolean state;
};
#define MT_LD100__STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_ld100__state__descriptor) \
    , 0 }


struct  _MtLd100__GetStateReq
{
  ProtobufCMessage base;
  int32_t addr;
};
#define MT_LD100__GET_STATE_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_ld100__get_state_req__descriptor) \
    , 0 }


struct  _MtLd100__GetStateRes
{
  ProtobufCMessage base;
  int32_t rescode;
  int32_t addr;
  MtLd100__State *state;
};
#define MT_LD100__GET_STATE_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_ld100__get_state_res__descriptor) \
    , 0, 0, NULL }


struct  _MtLd100__GetRelayReq
{
  ProtobufCMessage base;
  int32_t addr;
};
#define MT_LD100__GET_RELAY_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_ld100__get_relay_req__descriptor) \
    , 0 }


struct  _MtLd100__GetRelayRes
{
  ProtobufCMessage base;
  int32_t rescode;
  int32_t addr;
  protobuf_c_boolean state;
};
#define MT_LD100__GET_RELAY_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_ld100__get_relay_res__descriptor) \
    , 0, 0, 0 }


struct  _MtLd100__SetRelayReq
{
  ProtobufCMessage base;
  int32_t addr;
};
#define MT_LD100__SET_RELAY_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_ld100__set_relay_req__descriptor) \
    , 0 }


struct  _MtLd100__SetRelayRes
{
  ProtobufCMessage base;
  int32_t rescode;
};
#define MT_LD100__SET_RELAY_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mt_ld100__set_relay_res__descriptor) \
    , 0 }


/* MtLd100__GetAddrReq methods */
void   mt_ld100__get_addr_req__init
                     (MtLd100__GetAddrReq         *message);
size_t mt_ld100__get_addr_req__get_packed_size
                     (const MtLd100__GetAddrReq   *message);
size_t mt_ld100__get_addr_req__pack
                     (const MtLd100__GetAddrReq   *message,
                      uint8_t             *out);
size_t mt_ld100__get_addr_req__pack_to_buffer
                     (const MtLd100__GetAddrReq   *message,
                      ProtobufCBuffer     *buffer);
MtLd100__GetAddrReq *
       mt_ld100__get_addr_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_ld100__get_addr_req__free_unpacked
                     (MtLd100__GetAddrReq *message,
                      ProtobufCAllocator *allocator);
/* MtLd100__GetAddrRes methods */
void   mt_ld100__get_addr_res__init
                     (MtLd100__GetAddrRes         *message);
size_t mt_ld100__get_addr_res__get_packed_size
                     (const MtLd100__GetAddrRes   *message);
size_t mt_ld100__get_addr_res__pack
                     (const MtLd100__GetAddrRes   *message,
                      uint8_t             *out);
size_t mt_ld100__get_addr_res__pack_to_buffer
                     (const MtLd100__GetAddrRes   *message,
                      ProtobufCBuffer     *buffer);
MtLd100__GetAddrRes *
       mt_ld100__get_addr_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_ld100__get_addr_res__free_unpacked
                     (MtLd100__GetAddrRes *message,
                      ProtobufCAllocator *allocator);
/* MtLd100__SetAddrReq methods */
void   mt_ld100__set_addr_req__init
                     (MtLd100__SetAddrReq         *message);
size_t mt_ld100__set_addr_req__get_packed_size
                     (const MtLd100__SetAddrReq   *message);
size_t mt_ld100__set_addr_req__pack
                     (const MtLd100__SetAddrReq   *message,
                      uint8_t             *out);
size_t mt_ld100__set_addr_req__pack_to_buffer
                     (const MtLd100__SetAddrReq   *message,
                      ProtobufCBuffer     *buffer);
MtLd100__SetAddrReq *
       mt_ld100__set_addr_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_ld100__set_addr_req__free_unpacked
                     (MtLd100__SetAddrReq *message,
                      ProtobufCAllocator *allocator);
/* MtLd100__SetAddrRes methods */
void   mt_ld100__set_addr_res__init
                     (MtLd100__SetAddrRes         *message);
size_t mt_ld100__set_addr_res__get_packed_size
                     (const MtLd100__SetAddrRes   *message);
size_t mt_ld100__set_addr_res__pack
                     (const MtLd100__SetAddrRes   *message,
                      uint8_t             *out);
size_t mt_ld100__set_addr_res__pack_to_buffer
                     (const MtLd100__SetAddrRes   *message,
                      ProtobufCBuffer     *buffer);
MtLd100__SetAddrRes *
       mt_ld100__set_addr_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_ld100__set_addr_res__free_unpacked
                     (MtLd100__SetAddrRes *message,
                      ProtobufCAllocator *allocator);
/* MtLd100__State methods */
void   mt_ld100__state__init
                     (MtLd100__State         *message);
size_t mt_ld100__state__get_packed_size
                     (const MtLd100__State   *message);
size_t mt_ld100__state__pack
                     (const MtLd100__State   *message,
                      uint8_t             *out);
size_t mt_ld100__state__pack_to_buffer
                     (const MtLd100__State   *message,
                      ProtobufCBuffer     *buffer);
MtLd100__State *
       mt_ld100__state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_ld100__state__free_unpacked
                     (MtLd100__State *message,
                      ProtobufCAllocator *allocator);
/* MtLd100__GetStateReq methods */
void   mt_ld100__get_state_req__init
                     (MtLd100__GetStateReq         *message);
size_t mt_ld100__get_state_req__get_packed_size
                     (const MtLd100__GetStateReq   *message);
size_t mt_ld100__get_state_req__pack
                     (const MtLd100__GetStateReq   *message,
                      uint8_t             *out);
size_t mt_ld100__get_state_req__pack_to_buffer
                     (const MtLd100__GetStateReq   *message,
                      ProtobufCBuffer     *buffer);
MtLd100__GetStateReq *
       mt_ld100__get_state_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_ld100__get_state_req__free_unpacked
                     (MtLd100__GetStateReq *message,
                      ProtobufCAllocator *allocator);
/* MtLd100__GetStateRes methods */
void   mt_ld100__get_state_res__init
                     (MtLd100__GetStateRes         *message);
size_t mt_ld100__get_state_res__get_packed_size
                     (const MtLd100__GetStateRes   *message);
size_t mt_ld100__get_state_res__pack
                     (const MtLd100__GetStateRes   *message,
                      uint8_t             *out);
size_t mt_ld100__get_state_res__pack_to_buffer
                     (const MtLd100__GetStateRes   *message,
                      ProtobufCBuffer     *buffer);
MtLd100__GetStateRes *
       mt_ld100__get_state_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_ld100__get_state_res__free_unpacked
                     (MtLd100__GetStateRes *message,
                      ProtobufCAllocator *allocator);
/* MtLd100__GetRelayReq methods */
void   mt_ld100__get_relay_req__init
                     (MtLd100__GetRelayReq         *message);
size_t mt_ld100__get_relay_req__get_packed_size
                     (const MtLd100__GetRelayReq   *message);
size_t mt_ld100__get_relay_req__pack
                     (const MtLd100__GetRelayReq   *message,
                      uint8_t             *out);
size_t mt_ld100__get_relay_req__pack_to_buffer
                     (const MtLd100__GetRelayReq   *message,
                      ProtobufCBuffer     *buffer);
MtLd100__GetRelayReq *
       mt_ld100__get_relay_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_ld100__get_relay_req__free_unpacked
                     (MtLd100__GetRelayReq *message,
                      ProtobufCAllocator *allocator);
/* MtLd100__GetRelayRes methods */
void   mt_ld100__get_relay_res__init
                     (MtLd100__GetRelayRes         *message);
size_t mt_ld100__get_relay_res__get_packed_size
                     (const MtLd100__GetRelayRes   *message);
size_t mt_ld100__get_relay_res__pack
                     (const MtLd100__GetRelayRes   *message,
                      uint8_t             *out);
size_t mt_ld100__get_relay_res__pack_to_buffer
                     (const MtLd100__GetRelayRes   *message,
                      ProtobufCBuffer     *buffer);
MtLd100__GetRelayRes *
       mt_ld100__get_relay_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_ld100__get_relay_res__free_unpacked
                     (MtLd100__GetRelayRes *message,
                      ProtobufCAllocator *allocator);
/* MtLd100__SetRelayReq methods */
void   mt_ld100__set_relay_req__init
                     (MtLd100__SetRelayReq         *message);
size_t mt_ld100__set_relay_req__get_packed_size
                     (const MtLd100__SetRelayReq   *message);
size_t mt_ld100__set_relay_req__pack
                     (const MtLd100__SetRelayReq   *message,
                      uint8_t             *out);
size_t mt_ld100__set_relay_req__pack_to_buffer
                     (const MtLd100__SetRelayReq   *message,
                      ProtobufCBuffer     *buffer);
MtLd100__SetRelayReq *
       mt_ld100__set_relay_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_ld100__set_relay_req__free_unpacked
                     (MtLd100__SetRelayReq *message,
                      ProtobufCAllocator *allocator);
/* MtLd100__SetRelayRes methods */
void   mt_ld100__set_relay_res__init
                     (MtLd100__SetRelayRes         *message);
size_t mt_ld100__set_relay_res__get_packed_size
                     (const MtLd100__SetRelayRes   *message);
size_t mt_ld100__set_relay_res__pack
                     (const MtLd100__SetRelayRes   *message,
                      uint8_t             *out);
size_t mt_ld100__set_relay_res__pack_to_buffer
                     (const MtLd100__SetRelayRes   *message,
                      ProtobufCBuffer     *buffer);
MtLd100__SetRelayRes *
       mt_ld100__set_relay_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mt_ld100__set_relay_res__free_unpacked
                     (MtLd100__SetRelayRes *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MtLd100__GetAddrReq_Closure)
                 (const MtLd100__GetAddrReq *message,
                  void *closure_data);
typedef void (*MtLd100__GetAddrRes_Closure)
                 (const MtLd100__GetAddrRes *message,
                  void *closure_data);
typedef void (*MtLd100__SetAddrReq_Closure)
                 (const MtLd100__SetAddrReq *message,
                  void *closure_data);
typedef void (*MtLd100__SetAddrRes_Closure)
                 (const MtLd100__SetAddrRes *message,
                  void *closure_data);
typedef void (*MtLd100__State_Closure)
                 (const MtLd100__State *message,
                  void *closure_data);
typedef void (*MtLd100__GetStateReq_Closure)
                 (const MtLd100__GetStateReq *message,
                  void *closure_data);
typedef void (*MtLd100__GetStateRes_Closure)
                 (const MtLd100__GetStateRes *message,
                  void *closure_data);
typedef void (*MtLd100__GetRelayReq_Closure)
                 (const MtLd100__GetRelayReq *message,
                  void *closure_data);
typedef void (*MtLd100__GetRelayRes_Closure)
                 (const MtLd100__GetRelayRes *message,
                  void *closure_data);
typedef void (*MtLd100__SetRelayReq_Closure)
                 (const MtLd100__SetRelayReq *message,
                  void *closure_data);
typedef void (*MtLd100__SetRelayRes_Closure)
                 (const MtLd100__SetRelayRes *message,
                  void *closure_data);

/* --- services --- */

typedef struct _MtLd100__Ld100Service_Service MtLd100__Ld100Service_Service;
struct _MtLd100__Ld100Service_Service
{
  ProtobufCService base;
  void (*get_addr)(MtLd100__Ld100Service_Service *service,
                   const MtLd100__GetAddrReq *input,
                   MtLd100__GetAddrRes_Closure closure,
                   void *closure_data);
  void (*set_addr)(MtLd100__Ld100Service_Service *service,
                   const MtLd100__SetAddrReq *input,
                   MtLd100__SetAddrRes_Closure closure,
                   void *closure_data);
  void (*get_state)(MtLd100__Ld100Service_Service *service,
                    const MtLd100__GetStateReq *input,
                    MtLd100__GetStateReq_Closure closure,
                    void *closure_data);
  void (*get_relay)(MtLd100__Ld100Service_Service *service,
                    const MtLd100__GetRelayReq *input,
                    MtLd100__GetRelayRes_Closure closure,
                    void *closure_data);
  void (*set_relay)(MtLd100__Ld100Service_Service *service,
                    const MtLd100__SetRelayReq *input,
                    MtLd100__SetRelayRes_Closure closure,
                    void *closure_data);
};
typedef void (*MtLd100__Ld100Service_ServiceDestroy)(MtLd100__Ld100Service_Service *);
void mt_ld100__ld100_service__init (MtLd100__Ld100Service_Service *service,
                                    MtLd100__Ld100Service_ServiceDestroy destroy);
#define MT_LD100__LD100_SERVICE__BASE_INIT \
    { &mt_ld100__ld100_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define MT_LD100__LD100_SERVICE__INIT(function_prefix__) \
    { MT_LD100__LD100_SERVICE__BASE_INIT,\
      function_prefix__ ## get_addr,\
      function_prefix__ ## set_addr,\
      function_prefix__ ## get_state,\
      function_prefix__ ## get_relay,\
      function_prefix__ ## set_relay  }
void mt_ld100__ld100_service__get_addr(ProtobufCService *service,
                                       const MtLd100__GetAddrReq *input,
                                       MtLd100__GetAddrRes_Closure closure,
                                       void *closure_data);
void mt_ld100__ld100_service__set_addr(ProtobufCService *service,
                                       const MtLd100__SetAddrReq *input,
                                       MtLd100__SetAddrRes_Closure closure,
                                       void *closure_data);
void mt_ld100__ld100_service__get_state(ProtobufCService *service,
                                        const MtLd100__GetStateReq *input,
                                        MtLd100__GetStateReq_Closure closure,
                                        void *closure_data);
void mt_ld100__ld100_service__get_relay(ProtobufCService *service,
                                        const MtLd100__GetRelayReq *input,
                                        MtLd100__GetRelayRes_Closure closure,
                                        void *closure_data);
void mt_ld100__ld100_service__set_relay(ProtobufCService *service,
                                        const MtLd100__SetRelayReq *input,
                                        MtLd100__SetRelayRes_Closure closure,
                                        void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mt_ld100__get_addr_req__descriptor;
extern const ProtobufCMessageDescriptor mt_ld100__get_addr_res__descriptor;
extern const ProtobufCMessageDescriptor mt_ld100__set_addr_req__descriptor;
extern const ProtobufCMessageDescriptor mt_ld100__set_addr_res__descriptor;
extern const ProtobufCMessageDescriptor mt_ld100__state__descriptor;
extern const ProtobufCMessageDescriptor mt_ld100__get_state_req__descriptor;
extern const ProtobufCMessageDescriptor mt_ld100__get_state_res__descriptor;
extern const ProtobufCMessageDescriptor mt_ld100__get_relay_req__descriptor;
extern const ProtobufCMessageDescriptor mt_ld100__get_relay_res__descriptor;
extern const ProtobufCMessageDescriptor mt_ld100__set_relay_req__descriptor;
extern const ProtobufCMessageDescriptor mt_ld100__set_relay_res__descriptor;
extern const ProtobufCServiceDescriptor mt_ld100__ld100_service__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_mt_5fproto_5fld100_2eproto__INCLUDED */
