/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mt_proto_jxyl001.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mt_proto_jxyl001.pb-c.h"
void   temp__init
                     (Temp         *message)
{
  static const Temp init_value = TEMP__INIT;
  *message = init_value;
}
size_t temp__get_packed_size
                     (const Temp *message)
{
  assert(message->base.descriptor == &temp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t temp__pack
                     (const Temp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &temp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t temp__pack_to_buffer
                     (const Temp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &temp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Temp *
       temp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Temp *)
     protobuf_c_message_unpack (&temp__descriptor,
                                allocator, len, data);
}
void   temp__free_unpacked
                     (Temp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &temp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fog__init
                     (Fog         *message)
{
  static const Fog init_value = FOG__INIT;
  *message = init_value;
}
size_t fog__get_packed_size
                     (const Fog *message)
{
  assert(message->base.descriptor == &fog__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fog__pack
                     (const Fog *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fog__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fog__pack_to_buffer
                     (const Fog *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fog__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fog *
       fog__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fog *)
     protobuf_c_message_unpack (&fog__descriptor,
                                allocator, len, data);
}
void   fog__free_unpacked
                     (Fog *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fog__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_res__init
                     (DataRes         *message)
{
  static const DataRes init_value = DATA_RES__INIT;
  *message = init_value;
}
size_t data_res__get_packed_size
                     (const DataRes *message)
{
  assert(message->base.descriptor == &data_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_res__pack
                     (const DataRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_res__pack_to_buffer
                     (const DataRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataRes *
       data_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataRes *)
     protobuf_c_message_unpack (&data_res__descriptor,
                                allocator, len, data);
}
void   data_res__free_unpacked
                     (DataRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor temp__field_descriptors[4] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Temp, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Temp, temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hum",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Temp, hum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "votagetemp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Temp, votagetemp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temp__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  2,   /* field[2] = hum */
  1,   /* field[1] = temp */
  3,   /* field[3] = votagetemp */
};
static const ProtobufCIntRange temp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor temp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Temp",
  "Temp",
  "Temp",
  "",
  sizeof(Temp),
  4,
  temp__field_descriptors,
  temp__field_indices_by_name,
  1,  temp__number_ranges,
  (ProtobufCMessageInit) temp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fog__field_descriptors[3] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Fog, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frog",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Fog, frog),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "votagefog",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Fog, votagefog),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fog__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  1,   /* field[1] = frog */
  2,   /* field[2] = votagefog */
};
static const ProtobufCIntRange fog__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor fog__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Fog",
  "Fog",
  "Fog",
  "",
  sizeof(Fog),
  3,
  fog__field_descriptors,
  fog__field_indices_by_name,
  1,  fog__number_ranges,
  (ProtobufCMessageInit) fog__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_res__field_descriptors[3] =
{
  {
    "resCode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DataRes, rescode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temps",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DataRes, n_temps),
    offsetof(DataRes, temps),
    &temp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fogs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DataRes, n_fogs),
    offsetof(DataRes, fogs),
    &fog__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_res__field_indices_by_name[] = {
  2,   /* field[2] = fogs */
  0,   /* field[0] = resCode */
  1,   /* field[1] = temps */
};
static const ProtobufCIntRange data_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor data_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataRes",
  "DataRes",
  "DataRes",
  "",
  sizeof(DataRes),
  3,
  data_res__field_descriptors,
  data_res__field_indices_by_name,
  1,  data_res__number_ranges,
  (ProtobufCMessageInit) data_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor jxyl001_service__method_descriptors[1] =
{
  { "GetData", &google__protobuf__empty__descriptor, &data_res__descriptor },
};
const unsigned jxyl001_service__method_indices_by_name[] = {
  0         /* GetData */
};
const ProtobufCServiceDescriptor jxyl001_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "Jxyl001Service",
  "Jxyl001Service",
  "Jxyl001Service",
  "",
  1,
  jxyl001_service__method_descriptors,
  jxyl001_service__method_indices_by_name
};
void jxyl001_service__get_data(ProtobufCService *service,
                               const Google__Protobuf__Empty *input,
                               DataRes_Closure closure,
                               void *closure_data)
{
  assert(service->descriptor == &jxyl001_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void jxyl001_service__init (Jxyl001Service_Service *service,
                            Jxyl001Service_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &jxyl001_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
