/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mt_proto_airswitch001.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mt_proto_airswitch001.pb-c.h"
void   mt_airswitch001__state__init
                     (MtAirswitch001__State         *message)
{
  static const MtAirswitch001__State init_value = MT_AIRSWITCH001__STATE__INIT;
  *message = init_value;
}
size_t mt_airswitch001__state__get_packed_size
                     (const MtAirswitch001__State *message)
{
  assert(message->base.descriptor == &mt_airswitch001__state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__state__pack
                     (const MtAirswitch001__State *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__state__pack_to_buffer
                     (const MtAirswitch001__State *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__State *
       mt_airswitch001__state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__State *)
     protobuf_c_message_unpack (&mt_airswitch001__state__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__state__free_unpacked
                     (MtAirswitch001__State *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__op_state__init
                     (MtAirswitch001__OpState         *message)
{
  static const MtAirswitch001__OpState init_value = MT_AIRSWITCH001__OP_STATE__INIT;
  *message = init_value;
}
size_t mt_airswitch001__op_state__get_packed_size
                     (const MtAirswitch001__OpState *message)
{
  assert(message->base.descriptor == &mt_airswitch001__op_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__op_state__pack
                     (const MtAirswitch001__OpState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__op_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__op_state__pack_to_buffer
                     (const MtAirswitch001__OpState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__op_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__OpState *
       mt_airswitch001__op_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__OpState *)
     protobuf_c_message_unpack (&mt_airswitch001__op_state__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__op_state__free_unpacked
                     (MtAirswitch001__OpState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__op_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__ctrl__init
                     (MtAirswitch001__Ctrl         *message)
{
  static const MtAirswitch001__Ctrl init_value = MT_AIRSWITCH001__CTRL__INIT;
  *message = init_value;
}
size_t mt_airswitch001__ctrl__get_packed_size
                     (const MtAirswitch001__Ctrl *message)
{
  assert(message->base.descriptor == &mt_airswitch001__ctrl__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__ctrl__pack
                     (const MtAirswitch001__Ctrl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__ctrl__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__ctrl__pack_to_buffer
                     (const MtAirswitch001__Ctrl *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__ctrl__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__Ctrl *
       mt_airswitch001__ctrl__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__Ctrl *)
     protobuf_c_message_unpack (&mt_airswitch001__ctrl__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__ctrl__free_unpacked
                     (MtAirswitch001__Ctrl *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__ctrl__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__warn__init
                     (MtAirswitch001__Warn         *message)
{
  static const MtAirswitch001__Warn init_value = MT_AIRSWITCH001__WARN__INIT;
  *message = init_value;
}
size_t mt_airswitch001__warn__get_packed_size
                     (const MtAirswitch001__Warn *message)
{
  assert(message->base.descriptor == &mt_airswitch001__warn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__warn__pack
                     (const MtAirswitch001__Warn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__warn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__warn__pack_to_buffer
                     (const MtAirswitch001__Warn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__warn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__Warn *
       mt_airswitch001__warn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__Warn *)
     protobuf_c_message_unpack (&mt_airswitch001__warn__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__warn__free_unpacked
                     (MtAirswitch001__Warn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__warn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__data__init
                     (MtAirswitch001__Data         *message)
{
  static const MtAirswitch001__Data init_value = MT_AIRSWITCH001__DATA__INIT;
  *message = init_value;
}
size_t mt_airswitch001__data__get_packed_size
                     (const MtAirswitch001__Data *message)
{
  assert(message->base.descriptor == &mt_airswitch001__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__data__pack
                     (const MtAirswitch001__Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__data__pack_to_buffer
                     (const MtAirswitch001__Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__Data *
       mt_airswitch001__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__Data *)
     protobuf_c_message_unpack (&mt_airswitch001__data__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__data__free_unpacked
                     (MtAirswitch001__Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__config__init
                     (MtAirswitch001__Config         *message)
{
  static const MtAirswitch001__Config init_value = MT_AIRSWITCH001__CONFIG__INIT;
  *message = init_value;
}
size_t mt_airswitch001__config__get_packed_size
                     (const MtAirswitch001__Config *message)
{
  assert(message->base.descriptor == &mt_airswitch001__config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__config__pack
                     (const MtAirswitch001__Config *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__config__pack_to_buffer
                     (const MtAirswitch001__Config *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__Config *
       mt_airswitch001__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__Config *)
     protobuf_c_message_unpack (&mt_airswitch001__config__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__config__free_unpacked
                     (MtAirswitch001__Config *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__op_config__init
                     (MtAirswitch001__OpConfig         *message)
{
  static const MtAirswitch001__OpConfig init_value = MT_AIRSWITCH001__OP_CONFIG__INIT;
  *message = init_value;
}
size_t mt_airswitch001__op_config__get_packed_size
                     (const MtAirswitch001__OpConfig *message)
{
  assert(message->base.descriptor == &mt_airswitch001__op_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__op_config__pack
                     (const MtAirswitch001__OpConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__op_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__op_config__pack_to_buffer
                     (const MtAirswitch001__OpConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__op_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__OpConfig *
       mt_airswitch001__op_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__OpConfig *)
     protobuf_c_message_unpack (&mt_airswitch001__op_config__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__op_config__free_unpacked
                     (MtAirswitch001__OpConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__op_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__quality__init
                     (MtAirswitch001__Quality         *message)
{
  static const MtAirswitch001__Quality init_value = MT_AIRSWITCH001__QUALITY__INIT;
  *message = init_value;
}
size_t mt_airswitch001__quality__get_packed_size
                     (const MtAirswitch001__Quality *message)
{
  assert(message->base.descriptor == &mt_airswitch001__quality__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__quality__pack
                     (const MtAirswitch001__Quality *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__quality__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__quality__pack_to_buffer
                     (const MtAirswitch001__Quality *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__quality__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__Quality *
       mt_airswitch001__quality__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__Quality *)
     protobuf_c_message_unpack (&mt_airswitch001__quality__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__quality__free_unpacked
                     (MtAirswitch001__Quality *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__quality__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__op_quality__init
                     (MtAirswitch001__OpQuality         *message)
{
  static const MtAirswitch001__OpQuality init_value = MT_AIRSWITCH001__OP_QUALITY__INIT;
  *message = init_value;
}
size_t mt_airswitch001__op_quality__get_packed_size
                     (const MtAirswitch001__OpQuality *message)
{
  assert(message->base.descriptor == &mt_airswitch001__op_quality__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__op_quality__pack
                     (const MtAirswitch001__OpQuality *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__op_quality__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__op_quality__pack_to_buffer
                     (const MtAirswitch001__OpQuality *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__op_quality__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__OpQuality *
       mt_airswitch001__op_quality__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__OpQuality *)
     protobuf_c_message_unpack (&mt_airswitch001__op_quality__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__op_quality__free_unpacked
                     (MtAirswitch001__OpQuality *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__op_quality__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__get_req__init
                     (MtAirswitch001__GetReq         *message)
{
  static const MtAirswitch001__GetReq init_value = MT_AIRSWITCH001__GET_REQ__INIT;
  *message = init_value;
}
size_t mt_airswitch001__get_req__get_packed_size
                     (const MtAirswitch001__GetReq *message)
{
  assert(message->base.descriptor == &mt_airswitch001__get_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__get_req__pack
                     (const MtAirswitch001__GetReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__get_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__get_req__pack_to_buffer
                     (const MtAirswitch001__GetReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__get_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__GetReq *
       mt_airswitch001__get_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__GetReq *)
     protobuf_c_message_unpack (&mt_airswitch001__get_req__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__get_req__free_unpacked
                     (MtAirswitch001__GetReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__get_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__set_res__init
                     (MtAirswitch001__SetRes         *message)
{
  static const MtAirswitch001__SetRes init_value = MT_AIRSWITCH001__SET_RES__INIT;
  *message = init_value;
}
size_t mt_airswitch001__set_res__get_packed_size
                     (const MtAirswitch001__SetRes *message)
{
  assert(message->base.descriptor == &mt_airswitch001__set_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__set_res__pack
                     (const MtAirswitch001__SetRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__set_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__set_res__pack_to_buffer
                     (const MtAirswitch001__SetRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__set_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__SetRes *
       mt_airswitch001__set_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__SetRes *)
     protobuf_c_message_unpack (&mt_airswitch001__set_res__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__set_res__free_unpacked
                     (MtAirswitch001__SetRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__set_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__get_state_res__init
                     (MtAirswitch001__GetStateRes         *message)
{
  static const MtAirswitch001__GetStateRes init_value = MT_AIRSWITCH001__GET_STATE_RES__INIT;
  *message = init_value;
}
size_t mt_airswitch001__get_state_res__get_packed_size
                     (const MtAirswitch001__GetStateRes *message)
{
  assert(message->base.descriptor == &mt_airswitch001__get_state_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__get_state_res__pack
                     (const MtAirswitch001__GetStateRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__get_state_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__get_state_res__pack_to_buffer
                     (const MtAirswitch001__GetStateRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__get_state_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__GetStateRes *
       mt_airswitch001__get_state_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__GetStateRes *)
     protobuf_c_message_unpack (&mt_airswitch001__get_state_res__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__get_state_res__free_unpacked
                     (MtAirswitch001__GetStateRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__get_state_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__get_ctrl_res__init
                     (MtAirswitch001__GetCtrlRes         *message)
{
  static const MtAirswitch001__GetCtrlRes init_value = MT_AIRSWITCH001__GET_CTRL_RES__INIT;
  *message = init_value;
}
size_t mt_airswitch001__get_ctrl_res__get_packed_size
                     (const MtAirswitch001__GetCtrlRes *message)
{
  assert(message->base.descriptor == &mt_airswitch001__get_ctrl_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__get_ctrl_res__pack
                     (const MtAirswitch001__GetCtrlRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__get_ctrl_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__get_ctrl_res__pack_to_buffer
                     (const MtAirswitch001__GetCtrlRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__get_ctrl_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__GetCtrlRes *
       mt_airswitch001__get_ctrl_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__GetCtrlRes *)
     protobuf_c_message_unpack (&mt_airswitch001__get_ctrl_res__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__get_ctrl_res__free_unpacked
                     (MtAirswitch001__GetCtrlRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__get_ctrl_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__get_warn_res__init
                     (MtAirswitch001__GetWarnRes         *message)
{
  static const MtAirswitch001__GetWarnRes init_value = MT_AIRSWITCH001__GET_WARN_RES__INIT;
  *message = init_value;
}
size_t mt_airswitch001__get_warn_res__get_packed_size
                     (const MtAirswitch001__GetWarnRes *message)
{
  assert(message->base.descriptor == &mt_airswitch001__get_warn_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__get_warn_res__pack
                     (const MtAirswitch001__GetWarnRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__get_warn_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__get_warn_res__pack_to_buffer
                     (const MtAirswitch001__GetWarnRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__get_warn_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__GetWarnRes *
       mt_airswitch001__get_warn_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__GetWarnRes *)
     protobuf_c_message_unpack (&mt_airswitch001__get_warn_res__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__get_warn_res__free_unpacked
                     (MtAirswitch001__GetWarnRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__get_warn_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__get_data_res__init
                     (MtAirswitch001__GetDataRes         *message)
{
  static const MtAirswitch001__GetDataRes init_value = MT_AIRSWITCH001__GET_DATA_RES__INIT;
  *message = init_value;
}
size_t mt_airswitch001__get_data_res__get_packed_size
                     (const MtAirswitch001__GetDataRes *message)
{
  assert(message->base.descriptor == &mt_airswitch001__get_data_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__get_data_res__pack
                     (const MtAirswitch001__GetDataRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__get_data_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__get_data_res__pack_to_buffer
                     (const MtAirswitch001__GetDataRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__get_data_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__GetDataRes *
       mt_airswitch001__get_data_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__GetDataRes *)
     protobuf_c_message_unpack (&mt_airswitch001__get_data_res__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__get_data_res__free_unpacked
                     (MtAirswitch001__GetDataRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__get_data_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__get_config_res__init
                     (MtAirswitch001__GetConfigRes         *message)
{
  static const MtAirswitch001__GetConfigRes init_value = MT_AIRSWITCH001__GET_CONFIG_RES__INIT;
  *message = init_value;
}
size_t mt_airswitch001__get_config_res__get_packed_size
                     (const MtAirswitch001__GetConfigRes *message)
{
  assert(message->base.descriptor == &mt_airswitch001__get_config_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__get_config_res__pack
                     (const MtAirswitch001__GetConfigRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__get_config_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__get_config_res__pack_to_buffer
                     (const MtAirswitch001__GetConfigRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__get_config_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__GetConfigRes *
       mt_airswitch001__get_config_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__GetConfigRes *)
     protobuf_c_message_unpack (&mt_airswitch001__get_config_res__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__get_config_res__free_unpacked
                     (MtAirswitch001__GetConfigRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__get_config_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__get_quality_res__init
                     (MtAirswitch001__GetQualityRes         *message)
{
  static const MtAirswitch001__GetQualityRes init_value = MT_AIRSWITCH001__GET_QUALITY_RES__INIT;
  *message = init_value;
}
size_t mt_airswitch001__get_quality_res__get_packed_size
                     (const MtAirswitch001__GetQualityRes *message)
{
  assert(message->base.descriptor == &mt_airswitch001__get_quality_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__get_quality_res__pack
                     (const MtAirswitch001__GetQualityRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__get_quality_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__get_quality_res__pack_to_buffer
                     (const MtAirswitch001__GetQualityRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__get_quality_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__GetQualityRes *
       mt_airswitch001__get_quality_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__GetQualityRes *)
     protobuf_c_message_unpack (&mt_airswitch001__get_quality_res__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__get_quality_res__free_unpacked
                     (MtAirswitch001__GetQualityRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__get_quality_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__set_state_req__init
                     (MtAirswitch001__SetStateReq         *message)
{
  static const MtAirswitch001__SetStateReq init_value = MT_AIRSWITCH001__SET_STATE_REQ__INIT;
  *message = init_value;
}
size_t mt_airswitch001__set_state_req__get_packed_size
                     (const MtAirswitch001__SetStateReq *message)
{
  assert(message->base.descriptor == &mt_airswitch001__set_state_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__set_state_req__pack
                     (const MtAirswitch001__SetStateReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__set_state_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__set_state_req__pack_to_buffer
                     (const MtAirswitch001__SetStateReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__set_state_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__SetStateReq *
       mt_airswitch001__set_state_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__SetStateReq *)
     protobuf_c_message_unpack (&mt_airswitch001__set_state_req__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__set_state_req__free_unpacked
                     (MtAirswitch001__SetStateReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__set_state_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__set_config_req__init
                     (MtAirswitch001__SetConfigReq         *message)
{
  static const MtAirswitch001__SetConfigReq init_value = MT_AIRSWITCH001__SET_CONFIG_REQ__INIT;
  *message = init_value;
}
size_t mt_airswitch001__set_config_req__get_packed_size
                     (const MtAirswitch001__SetConfigReq *message)
{
  assert(message->base.descriptor == &mt_airswitch001__set_config_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__set_config_req__pack
                     (const MtAirswitch001__SetConfigReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__set_config_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__set_config_req__pack_to_buffer
                     (const MtAirswitch001__SetConfigReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__set_config_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__SetConfigReq *
       mt_airswitch001__set_config_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__SetConfigReq *)
     protobuf_c_message_unpack (&mt_airswitch001__set_config_req__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__set_config_req__free_unpacked
                     (MtAirswitch001__SetConfigReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__set_config_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__set_quality_req__init
                     (MtAirswitch001__SetQualityReq         *message)
{
  static const MtAirswitch001__SetQualityReq init_value = MT_AIRSWITCH001__SET_QUALITY_REQ__INIT;
  *message = init_value;
}
size_t mt_airswitch001__set_quality_req__get_packed_size
                     (const MtAirswitch001__SetQualityReq *message)
{
  assert(message->base.descriptor == &mt_airswitch001__set_quality_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__set_quality_req__pack
                     (const MtAirswitch001__SetQualityReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__set_quality_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__set_quality_req__pack_to_buffer
                     (const MtAirswitch001__SetQualityReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__set_quality_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__SetQualityReq *
       mt_airswitch001__set_quality_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__SetQualityReq *)
     protobuf_c_message_unpack (&mt_airswitch001__set_quality_req__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__set_quality_req__free_unpacked
                     (MtAirswitch001__SetQualityReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__set_quality_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_airswitch001__set_leak_test_req__init
                     (MtAirswitch001__SetLeakTestReq         *message)
{
  static const MtAirswitch001__SetLeakTestReq init_value = MT_AIRSWITCH001__SET_LEAK_TEST_REQ__INIT;
  *message = init_value;
}
size_t mt_airswitch001__set_leak_test_req__get_packed_size
                     (const MtAirswitch001__SetLeakTestReq *message)
{
  assert(message->base.descriptor == &mt_airswitch001__set_leak_test_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_airswitch001__set_leak_test_req__pack
                     (const MtAirswitch001__SetLeakTestReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_airswitch001__set_leak_test_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_airswitch001__set_leak_test_req__pack_to_buffer
                     (const MtAirswitch001__SetLeakTestReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_airswitch001__set_leak_test_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtAirswitch001__SetLeakTestReq *
       mt_airswitch001__set_leak_test_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtAirswitch001__SetLeakTestReq *)
     protobuf_c_message_unpack (&mt_airswitch001__set_leak_test_req__descriptor,
                                allocator, len, data);
}
void   mt_airswitch001__set_leak_test_req__free_unpacked
                     (MtAirswitch001__SetLeakTestReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_airswitch001__set_leak_test_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mt_airswitch001__state__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__State, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__state__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange mt_airswitch001__state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_airswitch001__state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.State",
  "State",
  "MtAirswitch001__State",
  "mt_airswitch001",
  sizeof(MtAirswitch001__State),
  1,
  mt_airswitch001__state__field_descriptors,
  mt_airswitch001__state__field_indices_by_name,
  1,  mt_airswitch001__state__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__op_state__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__OpState, data),
    &google__protobuf__bool_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__op_state__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange mt_airswitch001__op_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_airswitch001__op_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.OpState",
  "OpState",
  "MtAirswitch001__OpState",
  "mt_airswitch001",
  sizeof(MtAirswitch001__OpState),
  1,
  mt_airswitch001__op_state__field_descriptors,
  mt_airswitch001__op_state__field_indices_by_name,
  1,  mt_airswitch001__op_state__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__op_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__ctrl__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Ctrl, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__ctrl__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange mt_airswitch001__ctrl__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_airswitch001__ctrl__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.Ctrl",
  "Ctrl",
  "MtAirswitch001__Ctrl",
  "mt_airswitch001",
  sizeof(MtAirswitch001__Ctrl),
  1,
  mt_airswitch001__ctrl__field_descriptors,
  mt_airswitch001__ctrl__field_indices_by_name,
  1,  mt_airswitch001__ctrl__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__ctrl__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__warn__field_descriptors[13] =
{
  {
    "warnShort",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, warnshort),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warnWave",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, warnwave),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warnPowrHigh",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, warnpowrhigh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warnTempHigh",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, warntemphigh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warnLeak",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, warnleak),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warnCurrent",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, warncurrent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warnVotageHigh",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, warnvotagehigh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warnFire",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, warnfire),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warnVotageLow",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, warnvotagelow),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "noteVotageHigh",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, notevotagehigh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "noteVotageLow",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, notevotagelow),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "noteLeak",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, noteleak),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "noteCurrent",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Warn, notecurrent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__warn__field_indices_by_name[] = {
  12,   /* field[12] = noteCurrent */
  11,   /* field[11] = noteLeak */
  9,   /* field[9] = noteVotageHigh */
  10,   /* field[10] = noteVotageLow */
  5,   /* field[5] = warnCurrent */
  7,   /* field[7] = warnFire */
  4,   /* field[4] = warnLeak */
  2,   /* field[2] = warnPowrHigh */
  0,   /* field[0] = warnShort */
  3,   /* field[3] = warnTempHigh */
  6,   /* field[6] = warnVotageHigh */
  8,   /* field[8] = warnVotageLow */
  1,   /* field[1] = warnWave */
};
static const ProtobufCIntRange mt_airswitch001__warn__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 11, 7 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor mt_airswitch001__warn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.Warn",
  "Warn",
  "MtAirswitch001__Warn",
  "mt_airswitch001",
  sizeof(MtAirswitch001__Warn),
  13,
  mt_airswitch001__warn__field_descriptors,
  mt_airswitch001__warn__field_indices_by_name,
  2,  mt_airswitch001__warn__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__warn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__data__field_descriptors[7] =
{
  {
    "votage",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Data, votage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "leakCurrent",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Data, leakcurrent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Data, power),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Data, temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Data, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Data, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ctrl",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Data, ctrl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__data__field_indices_by_name[] = {
  6,   /* field[6] = ctrl */
  4,   /* field[4] = current */
  1,   /* field[1] = leakCurrent */
  2,   /* field[2] = power */
  5,   /* field[5] = state */
  3,   /* field[3] = temp */
  0,   /* field[0] = votage */
};
static const ProtobufCIntRange mt_airswitch001__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor mt_airswitch001__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.Data",
  "Data",
  "MtAirswitch001__Data",
  "mt_airswitch001",
  sizeof(MtAirswitch001__Data),
  7,
  mt_airswitch001__data__field_descriptors,
  mt_airswitch001__data__field_indices_by_name,
  1,  mt_airswitch001__data__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__config__field_descriptors[6] =
{
  {
    "votageHigh",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Config, votagehigh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "votageLow",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Config, votagelow),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "leakCurrentHigh",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Config, leakcurrenthigh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "powerHigh",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Config, powerhigh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tempHigh",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Config, temphigh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentHigh",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Config, currenthigh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__config__field_indices_by_name[] = {
  5,   /* field[5] = currentHigh */
  2,   /* field[2] = leakCurrentHigh */
  3,   /* field[3] = powerHigh */
  4,   /* field[4] = tempHigh */
  0,   /* field[0] = votageHigh */
  1,   /* field[1] = votageLow */
};
static const ProtobufCIntRange mt_airswitch001__config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor mt_airswitch001__config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.Config",
  "Config",
  "MtAirswitch001__Config",
  "mt_airswitch001",
  sizeof(MtAirswitch001__Config),
  6,
  mt_airswitch001__config__field_descriptors,
  mt_airswitch001__config__field_indices_by_name,
  1,  mt_airswitch001__config__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__op_config__field_descriptors[6] =
{
  {
    "votageHigh",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__OpConfig, votagehigh),
    &google__protobuf__float_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "votageLow",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__OpConfig, votagelow),
    &google__protobuf__float_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "leakCurrentHigh",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__OpConfig, leakcurrenthigh),
    &google__protobuf__float_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "powerHigh",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__OpConfig, powerhigh),
    &google__protobuf__float_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tempHigh",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__OpConfig, temphigh),
    &google__protobuf__float_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentHigh",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__OpConfig, currenthigh),
    &google__protobuf__float_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__op_config__field_indices_by_name[] = {
  5,   /* field[5] = currentHigh */
  2,   /* field[2] = leakCurrentHigh */
  3,   /* field[3] = powerHigh */
  4,   /* field[4] = tempHigh */
  0,   /* field[0] = votageHigh */
  1,   /* field[1] = votageLow */
};
static const ProtobufCIntRange mt_airswitch001__op_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor mt_airswitch001__op_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.OpConfig",
  "OpConfig",
  "MtAirswitch001__OpConfig",
  "mt_airswitch001",
  sizeof(MtAirswitch001__OpConfig),
  6,
  mt_airswitch001__op_config__field_descriptors,
  mt_airswitch001__op_config__field_indices_by_name,
  1,  mt_airswitch001__op_config__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__op_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__quality__field_descriptors[1] =
{
  {
    "quality",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__Quality, quality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__quality__field_indices_by_name[] = {
  0,   /* field[0] = quality */
};
static const ProtobufCIntRange mt_airswitch001__quality__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_airswitch001__quality__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.Quality",
  "Quality",
  "MtAirswitch001__Quality",
  "mt_airswitch001",
  sizeof(MtAirswitch001__Quality),
  1,
  mt_airswitch001__quality__field_descriptors,
  mt_airswitch001__quality__field_indices_by_name,
  1,  mt_airswitch001__quality__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__quality__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__op_quality__field_descriptors[1] =
{
  {
    "quality",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__OpQuality, quality),
    &google__protobuf__float_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__op_quality__field_indices_by_name[] = {
  0,   /* field[0] = quality */
};
static const ProtobufCIntRange mt_airswitch001__op_quality__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_airswitch001__op_quality__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.OpQuality",
  "OpQuality",
  "MtAirswitch001__OpQuality",
  "mt_airswitch001",
  sizeof(MtAirswitch001__OpQuality),
  1,
  mt_airswitch001__op_quality__field_descriptors,
  mt_airswitch001__op_quality__field_indices_by_name,
  1,  mt_airswitch001__op_quality__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__op_quality__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__get_req__field_descriptors[1] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetReq, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__get_req__field_indices_by_name[] = {
  0,   /* field[0] = addr */
};
static const ProtobufCIntRange mt_airswitch001__get_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_airswitch001__get_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.GetReq",
  "GetReq",
  "MtAirswitch001__GetReq",
  "mt_airswitch001",
  sizeof(MtAirswitch001__GetReq),
  1,
  mt_airswitch001__get_req__field_descriptors,
  mt_airswitch001__get_req__field_indices_by_name,
  1,  mt_airswitch001__get_req__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__get_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__set_res__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__SetRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__SetRes, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__set_res__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  0,   /* field[0] = code */
};
static const ProtobufCIntRange mt_airswitch001__set_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mt_airswitch001__set_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.SetRes",
  "SetRes",
  "MtAirswitch001__SetRes",
  "mt_airswitch001",
  sizeof(MtAirswitch001__SetRes),
  2,
  mt_airswitch001__set_res__field_descriptors,
  mt_airswitch001__set_res__field_indices_by_name,
  1,  mt_airswitch001__set_res__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__set_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__get_state_res__field_descriptors[3] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetStateRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetStateRes, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetStateRes, state),
    &mt_airswitch001__state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__get_state_res__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  0,   /* field[0] = code */
  2,   /* field[2] = state */
};
static const ProtobufCIntRange mt_airswitch001__get_state_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mt_airswitch001__get_state_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.GetStateRes",
  "GetStateRes",
  "MtAirswitch001__GetStateRes",
  "mt_airswitch001",
  sizeof(MtAirswitch001__GetStateRes),
  3,
  mt_airswitch001__get_state_res__field_descriptors,
  mt_airswitch001__get_state_res__field_indices_by_name,
  1,  mt_airswitch001__get_state_res__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__get_state_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__get_ctrl_res__field_descriptors[3] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetCtrlRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetCtrlRes, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ctrl",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetCtrlRes, ctrl),
    &mt_airswitch001__ctrl__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__get_ctrl_res__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  0,   /* field[0] = code */
  2,   /* field[2] = ctrl */
};
static const ProtobufCIntRange mt_airswitch001__get_ctrl_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mt_airswitch001__get_ctrl_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.GetCtrlRes",
  "GetCtrlRes",
  "MtAirswitch001__GetCtrlRes",
  "mt_airswitch001",
  sizeof(MtAirswitch001__GetCtrlRes),
  3,
  mt_airswitch001__get_ctrl_res__field_descriptors,
  mt_airswitch001__get_ctrl_res__field_indices_by_name,
  1,  mt_airswitch001__get_ctrl_res__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__get_ctrl_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__get_warn_res__field_descriptors[3] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetWarnRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetWarnRes, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warn",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetWarnRes, warn),
    &mt_airswitch001__warn__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__get_warn_res__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  0,   /* field[0] = code */
  2,   /* field[2] = warn */
};
static const ProtobufCIntRange mt_airswitch001__get_warn_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mt_airswitch001__get_warn_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.GetWarnRes",
  "GetWarnRes",
  "MtAirswitch001__GetWarnRes",
  "mt_airswitch001",
  sizeof(MtAirswitch001__GetWarnRes),
  3,
  mt_airswitch001__get_warn_res__field_descriptors,
  mt_airswitch001__get_warn_res__field_indices_by_name,
  1,  mt_airswitch001__get_warn_res__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__get_warn_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__get_data_res__field_descriptors[3] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetDataRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetDataRes, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetDataRes, data),
    &mt_airswitch001__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__get_data_res__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  0,   /* field[0] = code */
  2,   /* field[2] = data */
};
static const ProtobufCIntRange mt_airswitch001__get_data_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mt_airswitch001__get_data_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.GetDataRes",
  "GetDataRes",
  "MtAirswitch001__GetDataRes",
  "mt_airswitch001",
  sizeof(MtAirswitch001__GetDataRes),
  3,
  mt_airswitch001__get_data_res__field_descriptors,
  mt_airswitch001__get_data_res__field_indices_by_name,
  1,  mt_airswitch001__get_data_res__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__get_data_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__get_config_res__field_descriptors[3] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetConfigRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetConfigRes, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetConfigRes, config),
    &mt_airswitch001__config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__get_config_res__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  0,   /* field[0] = code */
  2,   /* field[2] = config */
};
static const ProtobufCIntRange mt_airswitch001__get_config_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mt_airswitch001__get_config_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.GetConfigRes",
  "GetConfigRes",
  "MtAirswitch001__GetConfigRes",
  "mt_airswitch001",
  sizeof(MtAirswitch001__GetConfigRes),
  3,
  mt_airswitch001__get_config_res__field_descriptors,
  mt_airswitch001__get_config_res__field_indices_by_name,
  1,  mt_airswitch001__get_config_res__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__get_config_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__get_quality_res__field_descriptors[3] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetQualityRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetQualityRes, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quality",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__GetQualityRes, quality),
    &mt_airswitch001__quality__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__get_quality_res__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  0,   /* field[0] = code */
  2,   /* field[2] = quality */
};
static const ProtobufCIntRange mt_airswitch001__get_quality_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mt_airswitch001__get_quality_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.GetQualityRes",
  "GetQualityRes",
  "MtAirswitch001__GetQualityRes",
  "mt_airswitch001",
  sizeof(MtAirswitch001__GetQualityRes),
  3,
  mt_airswitch001__get_quality_res__field_descriptors,
  mt_airswitch001__get_quality_res__field_indices_by_name,
  1,  mt_airswitch001__get_quality_res__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__get_quality_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__set_state_req__field_descriptors[2] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__SetStateReq, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__SetStateReq, state),
    &mt_airswitch001__op_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__set_state_req__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  1,   /* field[1] = state */
};
static const ProtobufCIntRange mt_airswitch001__set_state_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mt_airswitch001__set_state_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.SetStateReq",
  "SetStateReq",
  "MtAirswitch001__SetStateReq",
  "mt_airswitch001",
  sizeof(MtAirswitch001__SetStateReq),
  2,
  mt_airswitch001__set_state_req__field_descriptors,
  mt_airswitch001__set_state_req__field_indices_by_name,
  1,  mt_airswitch001__set_state_req__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__set_state_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__set_config_req__field_descriptors[2] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__SetConfigReq, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__SetConfigReq, config),
    &mt_airswitch001__op_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__set_config_req__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  1,   /* field[1] = config */
};
static const ProtobufCIntRange mt_airswitch001__set_config_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mt_airswitch001__set_config_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.SetConfigReq",
  "SetConfigReq",
  "MtAirswitch001__SetConfigReq",
  "mt_airswitch001",
  sizeof(MtAirswitch001__SetConfigReq),
  2,
  mt_airswitch001__set_config_req__field_descriptors,
  mt_airswitch001__set_config_req__field_indices_by_name,
  1,  mt_airswitch001__set_config_req__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__set_config_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__set_quality_req__field_descriptors[2] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__SetQualityReq, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quality",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__SetQualityReq, quality),
    &mt_airswitch001__op_quality__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__set_quality_req__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  1,   /* field[1] = quality */
};
static const ProtobufCIntRange mt_airswitch001__set_quality_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mt_airswitch001__set_quality_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.SetQualityReq",
  "SetQualityReq",
  "MtAirswitch001__SetQualityReq",
  "mt_airswitch001",
  sizeof(MtAirswitch001__SetQualityReq),
  2,
  mt_airswitch001__set_quality_req__field_descriptors,
  mt_airswitch001__set_quality_req__field_indices_by_name,
  1,  mt_airswitch001__set_quality_req__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__set_quality_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_airswitch001__set_leak_test_req__field_descriptors[1] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtAirswitch001__SetLeakTestReq, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_airswitch001__set_leak_test_req__field_indices_by_name[] = {
  0,   /* field[0] = addr */
};
static const ProtobufCIntRange mt_airswitch001__set_leak_test_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mt_airswitch001__set_leak_test_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.SetLeakTestReq",
  "SetLeakTestReq",
  "MtAirswitch001__SetLeakTestReq",
  "mt_airswitch001",
  sizeof(MtAirswitch001__SetLeakTestReq),
  1,
  mt_airswitch001__set_leak_test_req__field_descriptors,
  mt_airswitch001__set_leak_test_req__field_indices_by_name,
  1,  mt_airswitch001__set_leak_test_req__number_ranges,
  (ProtobufCMessageInit) mt_airswitch001__set_leak_test_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor mt_airswitch001__service__method_descriptors[10] =
{
  { "GetState", &mt_airswitch001__get_req__descriptor, &mt_airswitch001__get_state_res__descriptor },
  { "GetCtrl", &mt_airswitch001__get_req__descriptor, &mt_airswitch001__get_ctrl_res__descriptor },
  { "GetWarn", &mt_airswitch001__get_req__descriptor, &mt_airswitch001__get_warn_res__descriptor },
  { "GetData", &mt_airswitch001__get_req__descriptor, &mt_airswitch001__get_data_res__descriptor },
  { "GetConfig", &mt_airswitch001__get_req__descriptor, &mt_airswitch001__get_config_res__descriptor },
  { "GetQuality", &mt_airswitch001__get_req__descriptor, &mt_airswitch001__get_quality_res__descriptor },
  { "SetState", &mt_airswitch001__set_state_req__descriptor, &mt_airswitch001__set_res__descriptor },
  { "SetConfig", &mt_airswitch001__set_config_req__descriptor, &mt_airswitch001__set_res__descriptor },
  { "SetQuality", &mt_airswitch001__set_quality_req__descriptor, &mt_airswitch001__set_res__descriptor },
  { "SetLeakTest", &mt_airswitch001__set_leak_test_req__descriptor, &mt_airswitch001__set_res__descriptor },
};
const unsigned mt_airswitch001__service__method_indices_by_name[] = {
  4,        /* GetConfig */
  1,        /* GetCtrl */
  3,        /* GetData */
  5,        /* GetQuality */
  0,        /* GetState */
  2,        /* GetWarn */
  7,        /* SetConfig */
  9,        /* SetLeakTest */
  8,        /* SetQuality */
  6         /* SetState */
};
const ProtobufCServiceDescriptor mt_airswitch001__service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "mt_airswitch001.Service",
  "Service",
  "MtAirswitch001__Service",
  "mt_airswitch001",
  10,
  mt_airswitch001__service__method_descriptors,
  mt_airswitch001__service__method_indices_by_name
};
void mt_airswitch001__service__get_state(ProtobufCService *service,
                                         const MtAirswitch001__GetReq *input,
                                         MtAirswitch001__GetStateRes_Closure closure,
                                         void *closure_data)
{
  assert(service->descriptor == &mt_airswitch001__service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_airswitch001__service__get_ctrl(ProtobufCService *service,
                                        const MtAirswitch001__GetReq *input,
                                        MtAirswitch001__GetCtrlRes_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &mt_airswitch001__service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_airswitch001__service__get_warn(ProtobufCService *service,
                                        const MtAirswitch001__GetReq *input,
                                        MtAirswitch001__GetWarnRes_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &mt_airswitch001__service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_airswitch001__service__get_data(ProtobufCService *service,
                                        const MtAirswitch001__GetReq *input,
                                        MtAirswitch001__GetDataRes_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &mt_airswitch001__service__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_airswitch001__service__get_config(ProtobufCService *service,
                                          const MtAirswitch001__GetReq *input,
                                          MtAirswitch001__GetConfigRes_Closure closure,
                                          void *closure_data)
{
  assert(service->descriptor == &mt_airswitch001__service__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_airswitch001__service__get_quality(ProtobufCService *service,
                                           const MtAirswitch001__GetReq *input,
                                           MtAirswitch001__GetQualityRes_Closure closure,
                                           void *closure_data)
{
  assert(service->descriptor == &mt_airswitch001__service__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_airswitch001__service__set_state(ProtobufCService *service,
                                         const MtAirswitch001__SetStateReq *input,
                                         MtAirswitch001__SetRes_Closure closure,
                                         void *closure_data)
{
  assert(service->descriptor == &mt_airswitch001__service__descriptor);
  service->invoke(service, 6, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_airswitch001__service__set_config(ProtobufCService *service,
                                          const MtAirswitch001__SetConfigReq *input,
                                          MtAirswitch001__SetRes_Closure closure,
                                          void *closure_data)
{
  assert(service->descriptor == &mt_airswitch001__service__descriptor);
  service->invoke(service, 7, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_airswitch001__service__set_quality(ProtobufCService *service,
                                           const MtAirswitch001__SetQualityReq *input,
                                           MtAirswitch001__SetRes_Closure closure,
                                           void *closure_data)
{
  assert(service->descriptor == &mt_airswitch001__service__descriptor);
  service->invoke(service, 8, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_airswitch001__service__set_leak_test(ProtobufCService *service,
                                             const MtAirswitch001__SetLeakTestReq *input,
                                             MtAirswitch001__SetRes_Closure closure,
                                             void *closure_data)
{
  assert(service->descriptor == &mt_airswitch001__service__descriptor);
  service->invoke(service, 9, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_airswitch001__service__init (MtAirswitch001__Service_Service *service,
                                     MtAirswitch001__Service_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &mt_airswitch001__service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
