/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mt_proto_PRS3342AF.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mt_proto_PRS3342AF.pb-c.h"
void   mt_prs3342__data__init
                     (MtPrs3342__Data         *message)
{
  static const MtPrs3342__Data init_value = MT_PRS3342__DATA__INIT;
  *message = init_value;
}
size_t mt_prs3342__data__get_packed_size
                     (const MtPrs3342__Data *message)
{
  assert(message->base.descriptor == &mt_prs3342__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_prs3342__data__pack
                     (const MtPrs3342__Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_prs3342__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_prs3342__data__pack_to_buffer
                     (const MtPrs3342__Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_prs3342__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtPrs3342__Data *
       mt_prs3342__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtPrs3342__Data *)
     protobuf_c_message_unpack (&mt_prs3342__data__descriptor,
                                allocator, len, data);
}
void   mt_prs3342__data__free_unpacked
                     (MtPrs3342__Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_prs3342__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_prs3342__datas_res__init
                     (MtPrs3342__DatasRes         *message)
{
  static const MtPrs3342__DatasRes init_value = MT_PRS3342__DATAS_RES__INIT;
  *message = init_value;
}
size_t mt_prs3342__datas_res__get_packed_size
                     (const MtPrs3342__DatasRes *message)
{
  assert(message->base.descriptor == &mt_prs3342__datas_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_prs3342__datas_res__pack
                     (const MtPrs3342__DatasRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_prs3342__datas_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_prs3342__datas_res__pack_to_buffer
                     (const MtPrs3342__DatasRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_prs3342__datas_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtPrs3342__DatasRes *
       mt_prs3342__datas_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtPrs3342__DatasRes *)
     protobuf_c_message_unpack (&mt_prs3342__datas_res__descriptor,
                                allocator, len, data);
}
void   mt_prs3342__datas_res__free_unpacked
                     (MtPrs3342__DatasRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_prs3342__datas_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_prs3342__state__init
                     (MtPrs3342__State         *message)
{
  static const MtPrs3342__State init_value = MT_PRS3342__STATE__INIT;
  *message = init_value;
}
size_t mt_prs3342__state__get_packed_size
                     (const MtPrs3342__State *message)
{
  assert(message->base.descriptor == &mt_prs3342__state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_prs3342__state__pack
                     (const MtPrs3342__State *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_prs3342__state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_prs3342__state__pack_to_buffer
                     (const MtPrs3342__State *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_prs3342__state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtPrs3342__State *
       mt_prs3342__state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtPrs3342__State *)
     protobuf_c_message_unpack (&mt_prs3342__state__descriptor,
                                allocator, len, data);
}
void   mt_prs3342__state__free_unpacked
                     (MtPrs3342__State *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_prs3342__state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mt_prs3342__states_res__init
                     (MtPrs3342__StatesRes         *message)
{
  static const MtPrs3342__StatesRes init_value = MT_PRS3342__STATES_RES__INIT;
  *message = init_value;
}
size_t mt_prs3342__states_res__get_packed_size
                     (const MtPrs3342__StatesRes *message)
{
  assert(message->base.descriptor == &mt_prs3342__states_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mt_prs3342__states_res__pack
                     (const MtPrs3342__StatesRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mt_prs3342__states_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mt_prs3342__states_res__pack_to_buffer
                     (const MtPrs3342__StatesRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mt_prs3342__states_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtPrs3342__StatesRes *
       mt_prs3342__states_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtPrs3342__StatesRes *)
     protobuf_c_message_unpack (&mt_prs3342__states_res__descriptor,
                                allocator, len, data);
}
void   mt_prs3342__states_res__free_unpacked
                     (MtPrs3342__StatesRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mt_prs3342__states_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mt_prs3342__data__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MtPrs3342__Data, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MtPrs3342__Data, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_prs3342__data__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange mt_prs3342__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mt_prs3342__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_prs3342.Data",
  "Data",
  "MtPrs3342__Data",
  "mt_prs3342",
  sizeof(MtPrs3342__Data),
  2,
  mt_prs3342__data__field_descriptors,
  mt_prs3342__data__field_indices_by_name,
  1,  mt_prs3342__data__number_ranges,
  (ProtobufCMessageInit) mt_prs3342__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_prs3342__datas_res__field_descriptors[2] =
{
  {
    "resCode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtPrs3342__DatasRes, rescode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datas",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MtPrs3342__DatasRes, n_datas),
    offsetof(MtPrs3342__DatasRes, datas),
    &mt_prs3342__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_prs3342__datas_res__field_indices_by_name[] = {
  1,   /* field[1] = datas */
  0,   /* field[0] = resCode */
};
static const ProtobufCIntRange mt_prs3342__datas_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mt_prs3342__datas_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_prs3342.DatasRes",
  "DatasRes",
  "MtPrs3342__DatasRes",
  "mt_prs3342",
  sizeof(MtPrs3342__DatasRes),
  2,
  mt_prs3342__datas_res__field_descriptors,
  mt_prs3342__datas_res__field_indices_by_name,
  1,  mt_prs3342__datas_res__number_ranges,
  (ProtobufCMessageInit) mt_prs3342__datas_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_prs3342__state__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MtPrs3342__State, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtPrs3342__State, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_prs3342__state__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange mt_prs3342__state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mt_prs3342__state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_prs3342.State",
  "State",
  "MtPrs3342__State",
  "mt_prs3342",
  sizeof(MtPrs3342__State),
  2,
  mt_prs3342__state__field_descriptors,
  mt_prs3342__state__field_indices_by_name,
  1,  mt_prs3342__state__number_ranges,
  (ProtobufCMessageInit) mt_prs3342__state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mt_prs3342__states_res__field_descriptors[2] =
{
  {
    "resCode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MtPrs3342__StatesRes, rescode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "states",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MtPrs3342__StatesRes, n_states),
    offsetof(MtPrs3342__StatesRes, states),
    &mt_prs3342__state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mt_prs3342__states_res__field_indices_by_name[] = {
  0,   /* field[0] = resCode */
  1,   /* field[1] = states */
};
static const ProtobufCIntRange mt_prs3342__states_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mt_prs3342__states_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mt_prs3342.StatesRes",
  "StatesRes",
  "MtPrs3342__StatesRes",
  "mt_prs3342",
  sizeof(MtPrs3342__StatesRes),
  2,
  mt_prs3342__states_res__field_descriptors,
  mt_prs3342__states_res__field_indices_by_name,
  1,  mt_prs3342__states_res__number_ranges,
  (ProtobufCMessageInit) mt_prs3342__states_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor mt_prs3342__prs3342_afservice__method_descriptors[2] =
{
  { "GetDatas", &google__protobuf__empty__descriptor, &mt_prs3342__datas_res__descriptor },
  { "GetStates", &google__protobuf__empty__descriptor, &mt_prs3342__states_res__descriptor },
};
const unsigned mt_prs3342__prs3342_afservice__method_indices_by_name[] = {
  0,        /* GetDatas */
  1         /* GetStates */
};
const ProtobufCServiceDescriptor mt_prs3342__prs3342_afservice__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "mt_prs3342.PRS3342AFService",
  "PRS3342AFService",
  "MtPrs3342__PRS3342AFService",
  "mt_prs3342",
  2,
  mt_prs3342__prs3342_afservice__method_descriptors,
  mt_prs3342__prs3342_afservice__method_indices_by_name
};
void mt_prs3342__prs3342_afservice__get_datas(ProtobufCService *service,
                                              const Google__Protobuf__Empty *input,
                                              MtPrs3342__DatasRes_Closure closure,
                                              void *closure_data)
{
  assert(service->descriptor == &mt_prs3342__prs3342_afservice__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_prs3342__prs3342_afservice__get_states(ProtobufCService *service,
                                               const Google__Protobuf__Empty *input,
                                               MtPrs3342__StatesRes_Closure closure,
                                               void *closure_data)
{
  assert(service->descriptor == &mt_prs3342__prs3342_afservice__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_prs3342__prs3342_afservice__init (MtPrs3342__PRS3342AFService_Service *service,
                                          MtPrs3342__PRS3342AFService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &mt_prs3342__prs3342_afservice__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
