/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mt_proto_ota.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mt_proto_ota.pb-c.h"
void   version__init
                     (Version         *message)
{
  static const Version init_value = VERSION__INIT;
  *message = init_value;
}
size_t version__get_packed_size
                     (const Version *message)
{
  assert(message->base.descriptor == &version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t version__pack
                     (const Version *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t version__pack_to_buffer
                     (const Version *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Version *
       version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Version *)
     protobuf_c_message_unpack (&version__descriptor,
                                allocator, len, data);
}
void   version__free_unpacked
                     (Version *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_version_res__init
                     (GetVersionRes         *message)
{
  static const GetVersionRes init_value = GET_VERSION_RES__INIT;
  *message = init_value;
}
size_t get_version_res__get_packed_size
                     (const GetVersionRes *message)
{
  assert(message->base.descriptor == &get_version_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_version_res__pack
                     (const GetVersionRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_version_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_version_res__pack_to_buffer
                     (const GetVersionRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_version_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetVersionRes *
       get_version_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetVersionRes *)
     protobuf_c_message_unpack (&get_version_res__descriptor,
                                allocator, len, data);
}
void   get_version_res__free_unpacked
                     (GetVersionRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_version_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   op_ota_update__init
                     (OpOtaUpdate         *message)
{
  static const OpOtaUpdate init_value = OP_OTA_UPDATE__INIT;
  *message = init_value;
}
size_t op_ota_update__get_packed_size
                     (const OpOtaUpdate *message)
{
  assert(message->base.descriptor == &op_ota_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t op_ota_update__pack
                     (const OpOtaUpdate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &op_ota_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t op_ota_update__pack_to_buffer
                     (const OpOtaUpdate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &op_ota_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpOtaUpdate *
       op_ota_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpOtaUpdate *)
     protobuf_c_message_unpack (&op_ota_update__descriptor,
                                allocator, len, data);
}
void   op_ota_update__free_unpacked
                     (OpOtaUpdate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &op_ota_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_update_req__init
                     (OtaUpdateReq         *message)
{
  static const OtaUpdateReq init_value = OTA_UPDATE_REQ__INIT;
  *message = init_value;
}
size_t ota_update_req__get_packed_size
                     (const OtaUpdateReq *message)
{
  assert(message->base.descriptor == &ota_update_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_update_req__pack
                     (const OtaUpdateReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota_update_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_update_req__pack_to_buffer
                     (const OtaUpdateReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota_update_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaUpdateReq *
       ota_update_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaUpdateReq *)
     protobuf_c_message_unpack (&ota_update_req__descriptor,
                                allocator, len, data);
}
void   ota_update_req__free_unpacked
                     (OtaUpdateReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ota_update_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_update_res__init
                     (OtaUpdateRes         *message)
{
  static const OtaUpdateRes init_value = OTA_UPDATE_RES__INIT;
  *message = init_value;
}
size_t ota_update_res__get_packed_size
                     (const OtaUpdateRes *message)
{
  assert(message->base.descriptor == &ota_update_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_update_res__pack
                     (const OtaUpdateRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota_update_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_update_res__pack_to_buffer
                     (const OtaUpdateRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota_update_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaUpdateRes *
       ota_update_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaUpdateRes *)
     protobuf_c_message_unpack (&ota_update_res__descriptor,
                                allocator, len, data);
}
void   ota_update_res__free_unpacked
                     (OtaUpdateRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ota_update_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor version__field_descriptors[1] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Version, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned version__field_indices_by_name[] = {
  0,   /* field[0] = version */
};
static const ProtobufCIntRange version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor version__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Version",
  "Version",
  "Version",
  "",
  sizeof(Version),
  1,
  version__field_descriptors,
  version__field_indices_by_name,
  1,  version__number_ranges,
  (ProtobufCMessageInit) version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_version_res__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(GetVersionRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GetVersionRes, version),
    &version__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_version_res__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange get_version_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor get_version_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetVersionRes",
  "GetVersionRes",
  "GetVersionRes",
  "",
  sizeof(GetVersionRes),
  2,
  get_version_res__field_descriptors,
  get_version_res__field_indices_by_name,
  1,  get_version_res__number_ranges,
  (ProtobufCMessageInit) get_version_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor op_ota_update__field_descriptors[1] =
{
  {
    "url",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OpOtaUpdate, url),
    &google__protobuf__string_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned op_ota_update__field_indices_by_name[] = {
  0,   /* field[0] = url */
};
static const ProtobufCIntRange op_ota_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor op_ota_update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpOtaUpdate",
  "OpOtaUpdate",
  "OpOtaUpdate",
  "",
  sizeof(OpOtaUpdate),
  1,
  op_ota_update__field_descriptors,
  op_ota_update__field_indices_by_name,
  1,  op_ota_update__number_ranges,
  (ProtobufCMessageInit) op_ota_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ota_update_req__field_descriptors[1] =
{
  {
    "ota",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OtaUpdateReq, ota),
    &op_ota_update__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_update_req__field_indices_by_name[] = {
  0,   /* field[0] = ota */
};
static const ProtobufCIntRange ota_update_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ota_update_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OtaUpdateReq",
  "OtaUpdateReq",
  "OtaUpdateReq",
  "",
  sizeof(OtaUpdateReq),
  1,
  ota_update_req__field_descriptors,
  ota_update_req__field_indices_by_name,
  1,  ota_update_req__number_ranges,
  (ProtobufCMessageInit) ota_update_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ota_update_res__field_descriptors[1] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OtaUpdateRes, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_update_res__field_indices_by_name[] = {
  0,   /* field[0] = code */
};
static const ProtobufCIntRange ota_update_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ota_update_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OtaUpdateRes",
  "OtaUpdateRes",
  "OtaUpdateRes",
  "",
  sizeof(OtaUpdateRes),
  1,
  ota_update_res__field_descriptors,
  ota_update_res__field_indices_by_name,
  1,  ota_update_res__number_ranges,
  (ProtobufCMessageInit) ota_update_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor mt_ota_service__method_descriptors[2] =
{
  { "GetVersion", &google__protobuf__empty__descriptor, &get_version_res__descriptor },
  { "OtaUpdate", &ota_update_req__descriptor, &ota_update_res__descriptor },
};
const unsigned mt_ota_service__method_indices_by_name[] = {
  0,        /* GetVersion */
  1         /* OtaUpdate */
};
const ProtobufCServiceDescriptor mt_ota_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "MtOtaService",
  "MtOtaService",
  "MtOtaService",
  "",
  2,
  mt_ota_service__method_descriptors,
  mt_ota_service__method_indices_by_name
};
void mt_ota_service__get_version(ProtobufCService *service,
                                 const Google__Protobuf__Empty *input,
                                 GetVersionRes_Closure closure,
                                 void *closure_data)
{
  assert(service->descriptor == &mt_ota_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_ota_service__ota_update(ProtobufCService *service,
                                const OtaUpdateReq *input,
                                OtaUpdateRes_Closure closure,
                                void *closure_data)
{
  assert(service->descriptor == &mt_ota_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void mt_ota_service__init (MtOtaService_Service *service,
                           MtOtaService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &mt_ota_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
